### ISSUE TITLE
Impossible start Cassandra

### ISSUE THREAD

**Issue by charliy101** [Stratio/cassandra-lucene-index#111]
Hi @adelapena 
In test purposes were created only one table in Cassandra DB and one custom Lucene index based on that. Once Cassandra shut down, it has become impossible to start Cassandra DB up.
DB parameters:  Cassandra 3.2.1
The stack of exception is the next:

Exception (java.lang.RuntimeException) encountered during startup: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:424)
        at org.apache.cassandra.index.SecondaryIndexManager.createIndex(SecondaryIndexManager.java:159)
        at org.apache.cassandra.index.SecondaryIndexManager.addIndex(SecondaryIndexManager.java:185)
        at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:419)
        at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:367)
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:577)
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:554)
        at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:368)
        at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:305)
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:129)
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:106)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:250)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:551)
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:680)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:420)
        ... 13 more
Caused by: com.stratio.cassandra.lucene.IndexException: com.stratio.cassandra.lucene.IndexException: 'schema' is invalid : Unparseable JSON schema: Unexpected character ('I' (code 73)): was expecting a colon to separate field name and value
 at [Source: java.io.StringReader@1f32fa05; line: 8, column: 15]
        at com.stratio.cassandra.lucene.Index.<init>(Index.java:94)
        ... 18 more
Caused by: com.stratio.cassandra.lucene.IndexException: 'schema' is invalid : Unparseable JSON schema: Unexpected character ('I' (code 73)): was expecting a colon to separate field name and value
 at [Source: java.io.StringReader@1f32fa05; line: 8, column: 15]
        at com.stratio.cassandra.lucene.IndexOptions.parseSchema(IndexOptions.java:293)
        at com.stratio.cassandra.lucene.IndexOptions.<init>(IndexOptions.java:119)
        at com.stratio.cassandra.lucene.IndexService.<init>(IndexService.java:112)
        at com.stratio.cassandra.lucene.IndexServiceWide.<init>(IndexServiceWide.java:61)
        at com.stratio.cassandra.lucene.IndexService.build(IndexService.java:144)
        at com.stratio.cassandra.lucene.Index.<init>(Index.java:92)
        ... 18 more
Caused by: com.stratio.cassandra.lucene.IndexException: Unparseable JSON schema: Unexpected character ('I' (code 73)): was expecting a colon to separate field name and value
 at [Source: java.io.StringReader@1f32fa05; line: 8, column: 15]
        at com.stratio.cassandra.lucene.schema.SchemaBuilder.fromJson(SchemaBuilder.java:161)
        at com.stratio.cassandra.lucene.IndexOptions.parseSchema(IndexOptions.java:289)
        ... 23 more
Caused by: org.codehaus.jackson.JsonParseException: Unexpected character ('I' (code 73)): was expecting a colon to separate field name and value
 at [Source: java.io.StringReader@1f32fa05; line: 8, column: 15]
        at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:306)
        at org.codehaus.jackson.impl.ReaderBasedParser.nextToken(ReaderBasedParser.java:417)
        at org.codehaus.jackson.map.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:304)
        at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:249)
        at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33)
        at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)
        at org.codehaus.jackson.map.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:899)
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObjectUsingNonDefault(BeanDeserializer.java:733)
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:683)
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
        at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2723)
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1854)
        at com.stratio.cassandra.lucene.util.JsonSerializer.fromString(JsonSerializer.java:72)
        at com.stratio.cassandra.lucene.schema.SchemaBuilder.fromJson(SchemaBuilder.java:159)
        ... 24 more
ERROR 13:41:21 Exception encountered during startup
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:424) ~[apache-cassandra-3.2.1.jar:3.2.1]
        at org.apache.cassandra.index.SecondaryIndexManager.createIndex(SecondaryIndexManager.java:159) ~[apache-cassandra-3.2.1.jar:3.2.1]
        at org.apache.cassandra.index.SecondaryIndexManager.addIndex(SecondaryIndexManager.java:185) ~[apache-cassandra-3.2.1.jar:3.2.1]
        at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:419) ~[apache-cassandra-3.2.1.jar:3.2.1]
        at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:367) ~[apache-cassandra-3.2.1.jar:3.2.1]
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:577) ~[apache-cassandra-3.2.1.jar:3.2.1]
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:554) ~[apache-cassandra-3.2.1.jar:3.2.1]
        at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:368) ~[apache-cassandra-3.2.1.jar:3.2.1]
        at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:305) ~[apache-cassandra-3.2.1.jar:3.2.1]
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:129) ~[apache-cassandra-3.2.1.jar:3.2.1]
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:106) ~[apache-cassandra-3.2.1.jar:3.2.1]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:250) [apache-cassandra-3.2.1.jar:3.2.1]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:551) [apache-cassandra-3.2.1.jar:3.2.1]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:680) [apache-cassandra-3.2.1.jar:3.2.1]
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_74]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_74]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_74]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_74]
        at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:420) ~[apache-cassandra-3.2.1.jar:3.2.1]
        ... 13 common frames omitted
Caused by: com.stratio.cassandra.lucene.IndexException: com.stratio.cassandra.lucene.IndexException: 'schema' is invalid : Unparseable JSON schema: Unexpected character ('I' (code 73)): was expecting a colon to separate field name and value
 at [Source: java.io.StringReader@1f32fa05; line: 8, column: 15]
        at com.stratio.cassandra.lucene.Index.<init>(Index.java:94) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        ... 18 common frames omitted
Caused by: com.stratio.cassandra.lucene.IndexException: 'schema' is invalid : Unparseable JSON schema: Unexpected character ('I' (code 73)): was expecting a colon to separate field name and value
 at [Source: java.io.StringReader@1f32fa05; line: 8, column: 15]
        at com.stratio.cassandra.lucene.IndexOptions.parseSchema(IndexOptions.java:293) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexOptions.<init>(IndexOptions.java:119) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexService.<init>(IndexService.java:112) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexServiceWide.<init>(IndexServiceWide.java:61) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexService.build(IndexService.java:144) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.Index.<init>(Index.java:92) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        ... 18 common frames omitted
Caused by: com.stratio.cassandra.lucene.IndexException: Unparseable JSON schema: Unexpected character ('I' (code 73)): was expecting a colon to separate field name and value
 at [Source: java.io.StringReader@1f32fa05; line: 8, column: 15]
        at com.stratio.cassandra.lucene.schema.SchemaBuilder.fromJson(SchemaBuilder.java:161) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexOptions.parseSchema(IndexOptions.java:289) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        ... 23 common frames omitted
Caused by: org.codehaus.jackson.JsonParseException: Unexpected character ('I' (code 73)): was expecting a colon to separate field name and value
 at [Source: java.io.StringReader@1f32fa05; line: 8, column: 15]
        at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:306) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at org.codehaus.jackson.impl.ReaderBasedParser.nextToken(ReaderBasedParser.java:417) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at org.codehaus.jackson.map.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:304) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:249) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at org.codehaus.jackson.map.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:899) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObjectUsingNonDefault(BeanDeserializer.java:733) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:683) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2723) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1854) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.util.JsonSerializer.fromString(JsonSerializer.java:72) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.schema.SchemaBuilder.fromJson(SchemaBuilder.java:159) ~[cassandra-lucene-index-plugin-3.0.4.1-RC1-SNAPSHOT.jar:na]
        ... 24 common frames omitted

Test scenario in Cassandra:
1. Create table 
create table SOURCE(
	ID INT,
	SRC_ID INT,
	SRC_NAME TEXT,
	EFFECTIVE_DATE TIMESTAMP,
	DESCRIPTION TEXT,
	RAND_INT_VAL INT,
	PRIMARY KEY(SRC_ID, EFFECTIVE_DATE)
);

2. Create Lucene index
CREATE CUSTOM INDEX SOURCE_INDX ON source()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
	'refresh_seconds' : '1',
	'schema' : '{
        fields : {
            ID    	 		: {type : "integer"},
			SRC_ID 			: {type: "integer"},
            SRC_NAME  		: {type : "string"},
			EFFECTIVE_DATE  : {type : "date", pattern : "yyyy/MM/dd", sorted : true},
		    DESCRIPTION  	: {type : "string"},
			RAND_INT_VAL INT : {type: "integer"},
        }
    }'
};

3.
Then it was inserted some rows into SOURCE table.

4.Shut down the Cassandra DB
5. Start up Cassandra DB

Could you please take a look at this case?

Thanks in advance.

**Comment by adelapena** [comment]
Hi,

This repository contains [several versions of the plugin](https://github.com/Stratio/cassandra-lucene-index/releases). As you can read in [the documentation about requirements](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.3/doc/documentation.rst#requirements), each version of the plugin targets a specific Apache Cassandra release identified by the three first numbers of the plugin version. We don't provide support for [Cassandra tick-tock releases](http://www.planetcassandra.org/blog/cassandra-2-2-3-0-and-beyond/) such as 3.2.1, just for production-ready ones such as 3.0.4.

**Comment by charliy101** [comment]
Thanks a lot
