### ISSUE TITLE
Add a new node occur error

### ISSUE THREAD

**Issue by gpengtao** [Stratio/cassandra-lucene-index#113]
I use plugin 3.0.4 to my 3.0.4 cluster, I have three nodes, when I add a new node to the cluster, streem error occure:

```
ERROR [main] 2016-03-31 11:40:04,641 StorageService.java:1295 - Error while waiting on bootstrap to complete. Bootstrap will have to be restarted.
java.util.concurrent.ExecutionException: org.apache.cassandra.streaming.StreamException: Stream failed
    at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299) ~[guava-18.0.jar:na]
    at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286) ~[guava-18.0.jar:na]
    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116) ~[guava-18.0.jar:na]
    at org.apache.cassandra.service.StorageService.bootstrap(StorageService.java:1290) [apache-cassandra-3.0.4.jar:3.0.4]
    at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:966) [apache-cassandra-3.0.4.jar:3.0.4]
    at org.apache.cassandra.service.StorageService.initServer(StorageService.java:740) [apache-cassandra-3.0.4.jar:3.0.4]
    at org.apache.cassandra.service.StorageService.initServer(StorageService.java:610) [apache-cassandra-3.0.4.jar:3.0.4]
    at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:333) [apache-cassandra-3.0.4.jar:3.0.4]
    at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:551) [apache-cassandra-3.0.4.jar:3.0.4]
    at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:679) [apache-cassandra-3.0.4.jar:3.0.4]
Caused by: org.apache.cassandra.streaming.StreamException: Stream failed
    at org.apache.cassandra.streaming.management.StreamEventJMXNotifier.onFailure(StreamEventJMXNotifier.java:85) ~[apache-cassandra-3.0.4.jar:3.0.4]
    at com.google.common.util.concurrent.Futures$6.run(Futures.java:1310) ~[guava-18.0.jar:na]
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
    at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202) ~[guava-18.0.jar:na]
    at org.apache.cassandra.streaming.StreamResultFuture.maybeComplete(StreamResultFuture.java:210) ~[apache-cassandra-3.0.4.jar:3.0.4]
    at org.apache.cassandra.streaming.StreamResultFuture.handleSessionComplete(StreamResultFuture.java:186) ~[apache-cassandra-3.0.4.jar:3.0.4]
    at org.apache.cassandra.streaming.StreamSession.closeSession(StreamSession.java:430) ~[apache-cassandra-3.0.4.jar:3.0.4]
    at org.apache.cassandra.streaming.StreamSession.maybeCompleted(StreamSession.java:706) ~[apache-cassandra-3.0.4.jar:3.0.4]
    at org.apache.cassandra.streaming.StreamSession.taskCompleted(StreamSession.java:667) ~[apache-cassandra-3.0.4.jar:3.0.4]
    at org.apache.cassandra.streaming.StreamReceiveTask$OnCompletionRunnable.run(StreamReceiveTask.java:210) ~[apache-cassandra-3.0.4.jar:3.0.4]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_73]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_73]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_73]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_73]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_73]

```
I drop the keyspace of using Lucene index, then add a new node success.

**Comment by ealonsodb** [comment]
Hi @gpengtao 

I am trying to reproduce this issue without success. 
Have you reproduce this more than once? Does it always happen? 
Can you write here the keyspace, table and index creation queries??

Regards

**Comment by gpengtao** [comment]
I tried again, no repetition of this problem /(ㄒoㄒ)/~~, I close it.
