### ISSUE TITLE
java.lang.IllegalArgumentException: DocValuesField "y" is too large, must be <= 32766

### ISSUE THREAD

**Issue by craveica** [Stratio/cassandra-lucene-index#13]
```
ERROR [pool-4-thread-1] 2015-07-12 16:28:48,730 Log.java:53 - Unrecoverable error during asynchronously indexing
java.lang.IllegalArgumentException: DocValuesField "y" is too large, must be <= 32766
        at org.apache.lucene.index.SortedDocValuesWriter.addValue(SortedDocValuesWriter.java:68) ~[cassandra-lucene-index-plugin-2.1.8.0.jar:na]
        at org.apache.lucene.index.DefaultIndexingChain.indexDocValue(DefaultIndexingChain.java:434) ~[cassandra-lucene-index-plugin-2.1.8.0.jar:na]
        at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:376) ~[cassandra-lucene-index-plugin-2.1.8.0.jar:na]
        at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:300) ~[cassandra-lucene-index-plugin-2.1.8.0.jar:na]
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:232) ~[cassandra-lucene-index-plugin-2.1.8.0.jar:na]
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:458) ~[cassandra-lucene-index-plugin-2.1.8.0.jar:na]
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1350) ~[cassandra-lucene-index-plugin-2.1.8.0.jar:na]
        at com.stratio.cassandra.lucene.service.LuceneIndex.upsert(LuceneIndex.java:185) ~[cassandra-lucene-index-plugin-2.1.8.0.jar:na]
        at com.stratio.cassandra.lucene.service.RowServiceWide.doIndex(RowServiceWide.java:95) ~[cassandra-lucene-index-plugin-2.1.8.0.jar:na]
        at com.stratio.cassandra.lucene.service.RowService$2.run(RowService.java:170) ~[cassandra-lucene-index-plugin-2.1.8.0.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_45]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_45]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_45]

```

**Comment by adelapena** [comment]
Can you give more information in order to reproduce the issue? Which version are you using? How is your schema? How is the failing row?

**Comment by craveica** [comment]
I was upgrading from C* 2.1.5 to 2.1.8. I will try to reproduce with a new 2.1.8 cluster.

**Comment by adelapena** [comment]
2.1.5.0 uses Lucene 4.10.4, whereas 2.1.8.0 uses Lucene 5.1.0, which is incompatible. You should drop the index and built it again with 2.1.8.0.

**Comment by craveica** [comment]
It seams to work fine now.
Thanks.

**Comment by mbriot** [comment]
Hello I'm currently running the same issue on a cassandra 2.1.8 and the same version of the cassandra-lucene-index jar...

my schema : 
    CREATE KEYSPACE demo
    WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 1};
    USE demo;
    
    CREATE TABLE documents (
        id INT PRIMARY KEY,
        user TEXT,
        content TEXT,
        value INT,
        lucene TEXT
    );
    
    CREATE CUSTOM INDEX documents_index ON documents (lucene)
    USING 'com.stratio.cassandra.lucene.Index'
    WITH OPTIONS = {
        'refresh_seconds' : '1',
        'schema' : '{
            fields : {
                id    : {type : "integer"},
                user  : {type : "string"},
                content  : {type : "text", analyzer : "french"},
                value  : {type : "integer"}
            }
        }'
    };

the error during the insertion into cassandra : 
    java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: DocValuesField "content" is too large, must be <= 32766

The size of the file is 500ko, when I try with a 30 one it works fine.

Any idea ?

Thanks

**Comment by craveica** [comment]
It looks like there is a problem somewhere. Is lucene 5.x limitation/bug? I didn't encounter such issue with lucene 4.x. What do you think Andrés?

**Comment by adelapena** [comment]
It is due to a Lucene limitation in max token size:

https://issues.apache.org/jira/browse/LUCENE-5472
https://lucene.apache.org/core/5_1_0/core/org/apache/lucene/index/IndexWriter.html#addDocument(java.lang.Iterable)

However, the problem is affecting to Lucene DocValues, which are used to sort results. If you are not interested in sorting results by "content", you can omit DocValues setting "sorted" property to false:
```
CREATE CUSTOM INDEX documents_index ON documents (lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            id    : {type : "integer"},
            user  : {type : "string"},
            content  : {type : "text", analyzer : "french", sorted : false},
            value  : {type : "integer"}
        }
    }'
};
```
Probably this will solve the problem and, as an additional benefit, your index will be smaller.

**Comment by craveica** [comment]
This solution looks reasonable to me.

**Comment by mbriot** [comment]
Hello guys,
I guess the "sorting results" feature mean sorting by alphabetical order right ? If true this solution looks reasonable for me too.
It is not sorted by pertinence of the query ?

**Comment by adelapena** [comment]
Yes, that's exactly what it means. It's only used to be able to sort results by alphabetical or numerical order. If you use ``sorted:false`` you could still get the results sorted by relevance/pertinence, and also the index will be smaller.

**Comment by mbriot** [comment]
ok many thanks ! it's good for me that way. Congrats for the product it looks awesome ;)
