### ISSUE TITLE
Cassandra Shutting down after creating index

### ISSUE THREAD

**Issue by justinjoseph89** [Stratio/cassandra-lucene-index#133]
Hi,
We have two Cassandra server (2GB each) for test environment and one table contains more than 17 million records . Once i created indexing its started shutting down continuously. i am using Cassandra version 2.2.4 and corresponding Cassandra-lucene-index. In debug.log

> java.lang.OutOfMemoryError: Java heap space
        at java.nio.HeapByteBuffer.duplicate(HeapByteBuffer.java:107) ~[na:1.8.0_60]
        at org.apache.cassandra.db.composites.AbstractCType.sliceBytes(AbstractCType.java:353) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.composites.AbstractCompoundCellNameType.fromByteBuffer(AbstractCompoundCellNameType.java:99) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.composites.AbstractCType$Serializer.deserialize(AbstractCType.java:381) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.composites.AbstractCType$Serializer.deserialize(AbstractCType.java:365) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.composites.AbstractCellNameType$5.deserialize(AbstractCellNameType.java:117) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.composites.AbstractCellNameType$5.deserialize(AbstractCellNameType.java:109) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.ColumnSerializer.deserialize(ColumnSerializer.java:106) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.ColumnSerializer.deserialize(ColumnSerializer.java:101) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.ColumnFamilySerializer.deserialize(ColumnFamilySerializer.java:109) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.ColumnFamilySerializer.deserialize(ColumnFamilySerializer.java:88) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.Row$RowSerializer.deserialize(Row.java:74) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.Row$RowSerializer.deserialize(Row.java:79) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.RangeSliceReply$RangeSliceReplySerializer.deserialize(RangeSliceReply.java:80) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.RangeSliceReply$RangeSliceReplySerializer.deserialize(RangeSliceReply.java:66) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.net.MessageIn.read(MessageIn.java:99) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.net.IncomingTcpConnection.receiveMessage(IncomingTcpConnection.java:198) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.net.IncomingTcpConnection.receiveMessages(IncomingTcpConnection.java:175) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.net.IncomingTcpConnection.run(IncomingTcpConnection.java:91) ~[apache-cassandra-2.2.4.jar:2.2.4]
ERROR [SharedPool-Worker-2] 2016-05-17 06:05:19,458 JVMStabilityInspector.java:117 - JVM state determined to be unstable.  Exiting forcefully due to:
java.lang.OutOfMemoryError: Java heap space
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57) ~[na:1.8.0_60]
        at java.nio.ByteBuffer.allocate(ByteBuffer.java:335) ~[na:1.8.0_60]
        at org.apache.cassandra.utils.memory.SlabAllocator.getRegion(SlabAllocator.java:137) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.utils.memory.SlabAllocator.allocate(SlabAllocator.java:97) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.utils.memory.ContextAllocator.allocate(ContextAllocator.java:57) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.utils.memory.ContextAllocator.clone(ContextAllocator.java:47) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.utils.memory.MemtableBufferAllocator.clone(MemtableBufferAllocator.java:61) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.Memtable.put(Memtable.java:209) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1249) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.index.AbstractSimplePerColumnSecondaryIndex.insert(AbstractSimplePerColumnSecondaryIndex.java:125) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.index.SecondaryIndexManager$StandardUpdater.insert(SecondaryIndexManager.java:793) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.AtomicBTreeColumns$ColumnUpdater.apply(AtomicBTreeColumns.java:458) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.AtomicBTreeColumns$ColumnUpdater.apply(AtomicBTreeColumns.java:432) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.utils.btree.NodeBuilder.addNewKey(NodeBuilder.java:323) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.utils.btree.Builder.build(Builder.java:111) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.utils.btree.BTree.build(BTree.java:129) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.utils.btree.BTree.update(BTree.java:177) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.AtomicBTreeColumns.addAllWithSizeDelta(AtomicBTreeColumns.java:234) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.Memtable.put(Memtable.java:227) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1249) ~[apache-cassandra-2.2.4.jar:2.2.4]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_60]
        at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [apache-cassandra-2.2.4.jar:2.2.4]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
INFO  [Service Thread] 2016-05-17 06:05:19,480 StatusLogger.java:51 - Pool Name                    Active   Pending      Completed   Blocked  All Time Blocked
ERROR [MessagingService-Incoming-/10.128.133.89] 2016-05-17 06:05:19,481 JVMStabilityInspector.java:117 - JVM state determined to be unstable.  Exiting forcefully due to:
java.lang.OutOfMemoryError: Java heap space
        at java.nio.HeapByteBuffer.duplicate(HeapByteBuffer.java:107) ~[na:1.8.0_60]
        at org.apache.cassandra.db.composites.AbstractCType.sliceBytes(AbstractCType.java:353) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.composites.AbstractCompoundCellNameType.fromByteBuffer(AbstractCompoundCellNameType.java:99) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.composites.AbstractCType$Serializer.deserialize(AbstractCType.java:381) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.composites.AbstractCType$Serializer.deserialize(AbstractCType.java:365) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.composites.AbstractCellNameType$5.deserialize(AbstractCellNameType.java:117) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.composites.AbstractCellNameType$5.deserialize(AbstractCellNameType.java:109) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.ColumnSerializer.deserialize(ColumnSerializer.java:106) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.ColumnSerializer.deserialize(ColumnSerializer.java:101) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.ColumnFamilySerializer.deserialize(ColumnFamilySerializer.java:109) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.ColumnFamilySerializer.deserialize(ColumnFamilySerializer.java:88) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.Row$RowSerializer.deserialize(Row.java:74) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.Row$RowSerializer.deserialize(Row.java:79) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.RangeSliceReply$RangeSliceReplySerializer.deserialize(RangeSliceReply.java:80) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.db.RangeSliceReply$RangeSliceReplySerializer.deserialize(RangeSliceReply.java:66) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.net.MessageIn.read(MessageIn.java:99) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.net.IncomingTcpConnection.receiveMessage(IncomingTcpConnection.java:198) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.net.IncomingTcpConnection.receiveMessages(IncomingTcpConnection.java:175) ~[apache-cassandra-2.2.4.jar:2.2.4]
        at org.apache.cassandra.net.IncomingTcpConnection.run(IncomingTcpConnection.java:91) ~[apache-cassandra-2.2.4.jar:2.2.4]
INFO  [Service Thread] 2016-05-17 06:05:19,482 StatusLogger.java:55 - ReadStage                         0         0          20775         0                 0

And it will work if i remove that index. What i am doing wrong here?

**Comment by ealonsodb** [comment]
Hi @justinjoseph89 . We have some questions:

1.- What version of cassandra-lucene-index are you using??? Are you using 2.2.4.4??
2.- Is 2GB the data size in each node or the RAM size?? Can you give us the server specs??
3.- Can you give us the create Table and create index statement???
4.- What are your heap use configuration variables for cassandra?

Cheers

**Comment by justinjoseph89** [comment]
Hi,
1. No. Am using cassandra-lucene-index-plugin-2.2.4.3 
2.We are using Ubuntu 16.04 LTS with 2GB RAM and 2CPUs on Digital Ocean.
3. Table structure is ,
`CREATE TABLE test_space.test_table (
    column1 text,
    column2 text,
    column3 text,
    column4 text,
    column5 bigint,
    column6 text,
    column7 text,
    column8 int,
    column9 int,
    column10 text,
    column11 text,
    column12 text,
    column13 text,
    column14 text,
    column15 text,
    column16 text,
    column17 text,
    column18 text,
    column19 text,
    column20 text,
    column21 text,
    column22 text,
    column23 text,
    column24 text,
    column25 text,
    column26 text,
    column27 text,
    column28 text,
    column29 text,
    column30 text,
    column31 text,
    column32 text,
    column33 text,
    column34 text,
    column35 text,
    column36 text,
    column37 text,
    column38 text,
    column39 text,
    column40 text,
    column41 int,
    column42 int,
    column43 text,
    column44 text,
    lucene text,
    column45 text,
    column46 text,
    column47 text,
    column48 int,
    column49 text,
    column50 text,
    column51 text,
    column52 text,
    column53 text,
    column54 text,
    column55 text,
    column56 text,
    column57 int,
    column58 int,
    column59 text,
    column60 text,
    column61 text,
    column62 text,
    column63 text,
    column64 text,
    column65 text,
    column66 text,
    column67 text,
    column68 text,
    column69 text,
    column70 int,
    column71 text,
    column72 text,
    column73 text,
    column74 int,
    column75 text,
    column76 text,
    column77 text,
    column78 int,
    column79 text,
    PRIMARY KEY (column1, column2, column3, column4)
)`
 and index is,
`CREATE CUSTOM INDEX test_space_test_table_lucination ON test_space.test_table(lucene) USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
	'refresh_seconds': '1',
	'schema': '{ fields : {column1   : {type : "string"},column10 : {type : "string"},column2 : {type : "string"},column11 : {type : "string"},column4 : {type : "string",sorted:true},column23 : {type : "string"},column32 : {type : "string"},column33 : {type : "string"},column34 : {type : "string"},column41   : {type : "integer"},column55 : {type : "string"},column57 : {type : "string"},column66 : {type : "string"},column68 : {type : "long",sorted:true},column79: {type : "string"},column12: {type : "string"},column72: {type : "string"},column73: {type : "string"},column77: {type : "string"},column78: {type : "string"}}}'
}`

4. For heap configurations i am using default.

Thanks

**Comment by adelapena** [comment]
Hi,

Does it happen doing any specific Lucene search? If not, probably your JVM has not enough heap memory to manage Lucene and Cassandra at the same time. If I'm right, Cassandra takes 1/3 of the available memory, this is 666MB in the case of so modest hardware. You could try the following:

1. Increase Cassandra heap size
2. Use smaller values for [the index properties related to memory consumption](https://github.com/Stratio/cassandra-lucene-index/blob/2.2.4.3/doc/src/site/sphinx/documentation.rst#indexing): ram_buffer_mb, max_merge_mb and max_cached_mb.
3. Try to reduce Cassandra memory consumption (cache usage, etc.)

**Comment by justinjoseph89** [comment]
Hi,
Thanks for the reply . i will increase the memory and try.
