### ISSUE TITLE
Cassandara lucene index support for Spring Data cassandra?

### ISSUE THREAD

**Issue by Prasanthmv** [Stratio/cassandra-lucene-index#138]
Hi,

I am using spring data cassandra . I would like to use cassandra lucene index for quering the data . But while using thse queries getting following error
`Exception in thread "main" com.datastax.driver.core.exceptions.SyntaxError: line 1:98 missing EOF at '12341' (... associations WHERE lucene = '{query : {type : "match",field : "physicianid",value :'[12341]'}...)
at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:35)
at com.datastax.driver.core.DefaultResultSetFuture.extractCauseFromExecutionException(DefaultResultSetFuture.java:269)
at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:183)
at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:52)
at org.springframework.cassandra.core.CqlTemplate$12.doInSession(CqlTemplate.java:503)
at org.springframework.cassandra.core.CqlTemplate$12.doInSession(CqlTemplate.java:494)
at org.springframework.cassandra.core.CqlTemplate.doExecute(CqlTemplate.java:471)
at org.springframework.cassandra.core.CqlTemplate.doExecute(CqlTemplate.java:494)
at org.springframework.cassandra.core.CqlTemplate.doExecute(CqlTemplate.java:483)`

My query method is given below
`@Query("SELECT * FROM associations WHERE lucene = '{query : {type : \"match\",field : \"physicianid\",value :?0}}'")    
List<Associations> findByPhysicianId(String physicianid);`

Is there any way to escape the value ? Please help

**Comment by ealonsodb** [comment]
Hi @Prasanthmv:

Can you tell us which type is 'physicianid'?

Is the character '?' in the value part of the query intended or is a typo??

**Comment by Prasanthmv** [comment]
Hi,
Thanks for your replay . The type of physicianid i have given is text in Cassandra .

**Comment by adelapena** [comment]
Hi,

You can also try with this, using the query builder:
```
import static com.stratio.cassandra.lucene.builder.Builder.*;

...

@Query("SELECT * FROM associations WHERE lucene = ?") 
List<Associations> findByPhysicianId(String json);

List<Associations> findByPhysicianId(Integer physicianid) {
   String json = search().query(match("physicianid", physicianid)).build();
   return findByPhysicianId(json);
}
```
By the way, are you sure you want to do this search using a relevance query? Maybe a filter is enough:
```
SELECT * FROM associations WHERE lucene = '{filter : {type : "match",field : "physicianid",value :"12341"}}'
```
