### ISSUE TITLE
Removing lucene index column stops cassandra restart

### ISSUE THREAD

**Issue by nlacey** [Stratio/cassandra-lucene-index#153]
Create a lucene index on the table.
Drop one of the columns referenced within the lucene index.
Cassandra will continue to run.

Try and restart cassandra,
Cassandra won't start,  the cassandra log shows the following  core dump

Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: 'schema' is invalid : No column definition 'streams' for mapper 'streams'
org.apache.cassandra.exceptions.ConfigurationException: 'schema' is invalid : No column definition 'streams' for mapper 'streams'
        at com.stratio.cassandra.lucene.Index.validateOptions(Index.java:159)
        at org.apache.cassandra.db.index.SecondaryIndex.createInstance(SecondaryIndex.java:368)
        at org.apache.cassandra.db.index.SecondaryIndexManager.addIndexedColumn(SecondaryIndexManager.java:279)
        at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:407)
        at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:354)
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:535)
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:511)
        at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:342)
        at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:270)
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:116)
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:93)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:240)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:513)
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:622)
Caused by: com.stratio.cassandra.lucene.IndexException: 'schema' is invalid : No column definition 'streams' for mapper 'streams'
        at com.stratio.cassandra.lucene.IndexConfig.parseSchema(IndexConfig.java:324)
        at com.stratio.cassandra.lucene.IndexConfig.<init>(IndexConfig.java:98)
        at com.stratio.cassandra.lucene.Index.newIndexConfig(Index.java:213)
        at com.stratio.cassandra.lucene.Index.validateOptions(Index.java:156)
        ... 13 more
Caused by: com.stratio.cassandra.lucene.IndexException: No column definition 'streams' for mapper 'streams'
        at com.stratio.cassandra.lucene.schema.mapping.Mapper.validate(Mapper.java:251)
        at com.stratio.cassandra.lucene.schema.mapping.Mapper.validate(Mapper.java:162)
        at com.stratio.cassandra.lucene.schema.Schema.validate(Schema.java:156)

cassandra 2.2.3

**Comment by nlacey** [comment]
I believe I've downloaded the latest source from github and installed the build .jar file
thanks for any help

**Comment by adelapena** [comment]
Could you please be more specific about the specific plugin version? You should be using [2.2.3.2](https://github.com/Stratio/cassandra-lucene-index/tree/2.2.3.2) with Apache Cassandra 2.2.3, whereas the most recent sources in GitHub are for Apache Cassandra 3.0.7...

When using Cassandra 2.x, per row indexes should be removed before altering the base table schema. Indeed, Cassandra 3.x doesn't allow to remove indexed columns, requiring to delete the index before.

**Comment by nlacey** [comment]
Thanks for the response,
current githup  (cassandra-lucene-index branch-2.2.3)
cassandra 22-2.2.3-1

**Comment by nlacey** [comment]
I appreciate deleting indexes before altering the table, 
But my problem is what do I now?
I can't get into cqlsh in order to repair the table / delete the indexes

**Comment by adelapena** [comment]
Are you using Datastax Community version of Cassandra?

**Comment by nlacey** [comment]
yes

**Comment by adelapena** [comment]
You are having the same problem as reported in issue #108. The cause of the problem is that Cassandra doesn't check the existence of indexes before altering the base table schema. This is solved in Cassandra 3.x. We'll apply to 2.2.3 the same patch that was used in #108 for 2.1.8 ASAP.

**Comment by nlacey** [comment]
I can test out a branch for you (if needed)
Thanks!

**Comment by nlacey** [comment]
Worked great!  Thanks so much for your help

**Comment by adelapena** [comment]
You're very welcome :)

**Comment by jamlonga** [comment]
I got the same problem with plugin from branch 3.11.0.0.
In this case I alter the field name (in UDTs) without change it in the index (I create index for the field that data type is UDTs)
