### ISSUE TITLE
sort -> java.lang.ArrayIndexOutOfBoundsException: 3

### ISSUE THREAD

**Issue by whedro** [Stratio/cassandra-lucene-index#192]
Hi, 

when I try sort result, query finished with error 
```
ERROR [SharedPool-Worker-1] 2016-09-12 17:34:03,383 ErrorMessage.java:338 - Unexpected exception during request
java.lang.ArrayIndexOutOfBoundsException: 3
        at com.stratio.cassandra.lucene.column.ColumnsMapper.addColumns(ColumnsMapper.java:181) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.column.ColumnsMapper.addColumns(ColumnsMapper.java:182) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.column.ColumnsMapper.addColumns(ColumnsMapper.java:87) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.column.ColumnsMapper.addColumns(ColumnsMapper.java:62) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.column.ColumnsMapper.addColumns(ColumnsMapper.java:52) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexServiceSkinny.columns(IndexServiceSkinny.java:79) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexService.document(IndexService.java:294) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexService.process(IndexService.java:769) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexService.postProcess(IndexService.java:727) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexService.postProcess(IndexService.java:717) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.Index.lambda$postProcessorFor$5(Index.java:405) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at org.apache.cassandra.db.PartitionRangeReadCommand.postReconciliationProcessing(PartitionRangeReadCommand.java:291) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.service.StorageProxy.getRangeSlice(StorageProxy.java:2166) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.db.PartitionRangeReadCommand.execute(PartitionRangeReadCommand.java:163) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:273) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:234) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:78) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at com.stratio.cassandra.lucene.IndexQueryHandler.execute(IndexQueryHandler.java:181) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexQueryHandler.executeLuceneQuery(IndexQueryHandler.java:209) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexQueryHandler.processStatement(IndexQueryHandler.java:146) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexQueryHandler.process(IndexQueryHandler.java:129) ~[cassandra-lucene-index-plugin-3.7.2-RC1-SNAPSHOT.jar:na]
        at org.apache.cassandra.transport.messages.QueryMessage.execute(QueryMessage.java:115) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:507) [apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.transport.Message$Dispatcher.channelRead0(Message.java:401) [apache-cassandra-3.7.0.jar:3.7.0]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32) [netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:283) [netty-all-4.0.36.Final.jar:4.0.36.Final]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:164) [apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [apache-cassandra-3.7.0.jar:3.7.0]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
```

**select**
```
SELECT * FROM reservations WHERE expr(reservations_index, '{
filter: {
	type:"boolean",
		must:[
			{type:"contains",field:"services.room",values:[4,5,8,9]}
		]
	},
	sort : 
   {
     fields: [ 
			{field :"reservationnumber", reverse : true}
			] 
   }	
}') LIMIT 100
```
**index**
```
CREATE CUSTOM INDEX reservations_index ON reservations ()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            "id": { type: "uuid" },
            "services.reservationserviceid": { type: "string" },
            "services.fullprice": { type: "float" },
            "services.staff": { type: "integer" },
            "services.room": { type: "integer" },
            "services.datefrom": { type: "date", pattern: "yyyy-MM-dd HH:mm:ss" },
            "services.dateto": { type: "date", pattern: "yyyy-MM-dd HH:mm:ss" },
            "services.category": { type: "string" },
            "daterange": { type: "date_range", from: "services.datefrom", to: "services.dateto", pattern: "yyyy-MM-dd HH:mm:ss" },
            "reservationnumber": { type: "string" },
            "reservationdate": {type: "date", pattern: "yyyy-MM-dd HH:mm:ss" },
            "appoitmenttype": { type: "integer" }
        }
    }'
};
```

Thanx for help..
Michal

**Comment by adelapena** [comment]
Hi @whedro,

Could you please paste the schema of the table?

Which version of Apache Cassandra are you using?

Thanks,

**Comment by whedro** [comment]
Hi @adelapena, 

Apache Cassandra is in version 3.7

**table**
```sql
CREATE TABLE reservations (
    id uuid,
    appoitmenttype int,
    history list<frozen<reservationhistorytype>>,
    modified frozen<modifiedtype>,
    note text,
    payments list<frozen<reservationpaymenttype>>,
    reservationdate timestamp,
    reservationnumber text,
    services list<frozen<reservationservicetype>>,
    sourcetype text,
    PRIMARY KEY (id)
)
```

**Comment by whedro** [comment]
At first we try it on field *reservationdate* and then *reservationnumber*, but still result ..

**Comment by adelapena** [comment]
Thanks @whedro. In order to be able to reproduce the issue I would also need the definition of the UDTs in the table schema.

**Comment by whedro** [comment]
**reservationhistorytype**
```
CREATE TYPE reservationhistorytype (
    historydate timestamp,
    userid int,
    note text
);
```
**modifiedtype**

**Comment by whedro** [comment]
**Note:** without `sort` working right..

**Comment by adelapena** [comment]
Thanks for the definitions. I've inserted some data with your schema but I'm not able to reproduce the error. Could you please paste the expected results of the query, or the results when there is no ``sort``? If you don't want the data to be public, you can send it to ``andres at stratio dot com``.

**Comment by whedro** [comment]
Hi @adelapena 
today we truncate table, because there was inconsistence data and we rebuiled index too. Now is it OK.. 
Thanks for you time ...
M.
