### ISSUE TITLE
Start Cassandra after compile lucene-index-3.7.2 from releases

### ISSUE THREAD

**Issue by whedro** [Stratio/cassandra-lucene-index#197]
```
ERROR [main] 2016-09-14 13:45:54,446 CassandraDaemon.java:731 - Exception encountered during startup
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:424) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.index.SecondaryIndexManager.createIndex(SecondaryIndexManager.java:159) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.index.SecondaryIndexManager.addIndex(SecondaryIndexManager.java:185) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:429) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:377) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:592) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:569) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:383) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:320) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:130) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:107) ~[apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:281) [apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:585) [apache-cassandra-3.7.0.jar:3.7.0]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:714) [apache-cassandra-3.7.0.jar:3.7.0]
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_101]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_101]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_101]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_101]
        at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:420) ~[apache-cassandra-3.7.0.jar:3.7.0]
        ... 13 common frames omitted
Caused by: com.stratio.cassandra.lucene.IndexException: com.stratio.cassandra.lucene.IndexException: 'schema' is invalid : Unparseable JSON schema: Unrecognized field "indexed" (Class com.stratio.cassandra.lucene.schema.mapping.builder.IntegerMapperBuilder), not marked as ignorable
 at [Source: java.io.StringReader@48c52839; line: 8, column: 58] (through reference chain: com.stratio.cassandra.lucene.schema.mapping.builder.IntegerMapperBuilder["indexed"]): {
        fields : {
            name     : {type : "string"},
            gender   : {type : "string", validated : true},
            animal   : {type : "string"},
            age      : {type : "integer"},
            food     : {type : "string"},
            number   : {type : "integer", indexed : false, sorted : true},
            bool     : {type : "boolean"},
            date     : {type : "date", sorted : true, validated : true, pattern : "yyyy/MM/dd"},
            duration : {type : "date_range", from : "start_date", to : "stop_date", pattern : "yyyy/MM/dd"},
            place    : {type : "geo_point", latitude : "latitude", longitude : "longitude", sorted : true},
            mapz     : {type : "string", sorted : true},
            setz     : {type : "string"},
            listz    : {type : "string"}
        }
    }
        at com.stratio.cassandra.lucene.Index.<init>(Index.java:90) ~[cassandra-lucene-index-plugin-3.7.2.jar:na]
        ... 18 common frames omitted
Caused by: com.stratio.cassandra.lucene.IndexException: 'schema' is invalid : Unparseable JSON schema: Unrecognized field "indexed" (Class com.stratio.cassandra.lucene.schema.mapping.builder.IntegerMapperBuilder), not marked as ignorable
 at [Source: java.io.StringReader@48c52839; line: 8, column: 58] (through reference chain: com.stratio.cassandra.lucene.schema.mapping.builder.IntegerMapperBuilder["indexed"]): {
        fields : {
            name     : {type : "string"},
            gender   : {type : "string", validated : true},
            animal   : {type : "string"},
            age      : {type : "integer"},
            food     : {type : "string"},
            number   : {type : "integer", indexed : false, sorted : true},
            bool     : {type : "boolean"},
            date     : {type : "date", sorted : true, validated : true, pattern : "yyyy/MM/dd"},
            duration : {type : "date_range", from : "start_date", to : "stop_date", pattern : "yyyy/MM/dd"},
            place    : {type : "geo_point", latitude : "latitude", longitude : "longitude", sorted : true},
            mapz     : {type : "string", sorted : true},
            setz     : {type : "string"},
            listz    : {type : "string"}
        }
    }
        at com.stratio.cassandra.lucene.IndexOptions.parseSchema(IndexOptions.java:270) ~[cassandra-lucene-index-plugin-3.7.2.jar:na]
        at com.stratio.cassandra.lucene.IndexOptions.<init>(IndexOptions.java:111) ~[cassandra-lucene-index-plugin-3.7.2.jar:na]
        at com.stratio.cassandra.lucene.IndexService.<init>(IndexService.java:111) ~[cassandra-lucene-index-plugin-3.7.2.jar:na]
        at com.stratio.cassandra.lucene.IndexServiceWide.<init>(IndexServiceWide.java:60) ~[cassandra-lucene-index-plugin-3.7.2.jar:na]
        at com.stratio.cassandra.lucene.IndexService.build(IndexService.java:182) ~[cassandra-lucene-index-plugin-3.7.2.jar:na]
        at com.stratio.cassandra.lucene.Index.<init>(Index.java:88) ~[cassandra-lucene-index-plugin-3.7.2.jar:na]
        ... 18 common frames omitted
Caused by: com.stratio.cassandra.lucene.IndexException: Unparseable JSON schema: Unrecognized field "indexed" (Class com.stratio.cassandra.lucene.schema.mapping.builder.IntegerMapperBuilder), not marked as ignorable
 at [Source: java.io.StringReader@48c52839; line: 8, column: 58] (through reference chain: com.stratio.cassandra.lucene.schema.mapping.builder.IntegerMapperBuilder["indexed"]): {
        fields : {
            name     : {type : "string"},
            gender   : {type : "string", validated : true},
            animal   : {type : "string"},
            age      : {type : "integer"},
            food     : {type : "string"},
            number   : {type : "integer", indexed : false, sorted : true},
            bool     : {type : "boolean"},
            date     : {type : "date", sorted : true, validated : true, pattern : "yyyy/MM/dd"},
            duration : {type : "date_range", from : "start_date", to : "stop_date", pattern : "yyyy/MM/dd"},
            place    : {type : "geo_point", latitude : "latitude", longitude : "longitude", sorted : true},
            mapz     : {type : "string", sorted : true},
            setz     : {type : "string"},
            listz    : {type : "string"}
        }
    }
        at com.stratio.cassandra.lucene.schema.SchemaBuilder.fromJson(SchemaBuilder.java:158) ~[cassandra-lucene-index-plugin-3.7.2.jar:na]
        at com.stratio.cassandra.lucene.IndexOptions.parseSchema(IndexOptions.java:262) ~[cassandra-lucene-index-plugin-3.7.2.jar:na]
        ... 23 common frames omitted
Caused by: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "indexed" (Class com.stratio.cassandra.lucene.schema.mapping.builder.IntegerMapperBuilder), not marked as ignorable
 at [Source: java.io.StringReader@48c52839; line: 8, column: 58] (through reference chain: com.stratio.cassandra.lucene.schema.mapping.builder.IntegerMapperBuilder["indexed"])
        at org.codehaus.jackson.map.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:53) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownFieldException(StdDeserializationContext.java:267) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.std.StdDeserializer.reportUnknownProperty(StdDeserializer.java:649) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:635) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.BeanDeserializer.handleUnknownProperty(BeanDeserializer.java:1355) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:717) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:600) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:84) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:89) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:321) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:249) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:899) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObjectUsingNonDefault(BeanDeserializer.java:733) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:683) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2723) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1854) ~[jackson-mapper-asl-1.9.2.jar:1.9.2]
        at com.stratio.cassandra.lucene.util.JsonSerializer.fromString(JsonSerializer.java:70) ~[cassandra-lucene-index-plugin-3.7.2.jar:na]
        at com.stratio.cassandra.lucene.schema.SchemaBuilder.fromJson(SchemaBuilder.java:156) ~[cassandra-lucene-index-plugin-3.7.2.jar:na]
        ... 24 common frames omitted
```

**Comment by ealonsodb** [comment]
Hi @whedro 

When you upgrade cassandra-lucene-index you need to follow the [upgrade](https://github.com/Stratio/cassandra-lucene-index/blob/3.7.2/doc/documentation.rst#upgrade) instructions in doc.

The exception says that the integer mapper over 'number' column cannot be deserialized because of 'indexed' property. 

If you carefully read the related [doc-3.7.2](https://github.com/Stratio/cassandra-lucene-index/blob/3.7.2/doc/documentation.rst#integer-mapper) you will see that integer mapper has changed and it has no more the 'indexed' and 'sorted' parameters. 

When upgrading, if the 'CREATE CUSTOM INDEX' query changes from one version to another you have to:
-Drop the index with old version.
-Replace jar.
-Create a new index with new version and new syntax. 

So, replace the new jar with old one, start cassandra, drop index, stop cassandra, update jar, start cassandra, create index. 

If you dont have a copy of the old jar, please tell me and i will generate one for you.

Cheers

**Comment by adelapena** [comment]
To add some more information, ``indexed`` and ``sorted`` options where removed in 3.0.5.1 and 3.5.1 as part of the upgrade to Apache Lucene 5.5.1. 

The new Lucene's approach for doc values fields make unnecessary the distinction between ``indexed`` and ``sorted`` because the indexable fields used for sorting are also required when searching using the ``doc_values`` option that several queries types offer. This new ``doc_values`` option significantly improves the performance of searches with low restrictiveness.

Anyway, thanks for reporting.

**Comment by whedro** [comment]
@ealonsodb 
thanks for help with index .... after drop indexs, compile lucene index, start cassandra a again recreate indexes works fine.

@adelapena Thank for info

@all  .... good job with this .....
Michal

**Comment by adelapena** [comment]
You are welcome
