### ISSUE TITLE
Upgrade from 2.2.4 to 3.7: Out of Memory building Secondary Indexes

### ISSUE THREAD

**Issue by drudkhsg** [Stratio/cassandra-lucene-index#203]
I just upgraded Cassandra from 2.2.4 to 3.7. I had to drop existing indexes somehow due to unrecognized custom indexes error in 3.7.

When I re-create lucene indexes, Cassandra threw an error on start and won't boot.

```
ERROR [CompactionExecutor:2] 2016-09-27 08:22:56,725 CassandraDaemon.java:217 - Exception in thread Thread[CompactionExecutor:2,1,main]
java.lang.OutOfMemoryError: Java heap space
ERROR [SecondaryIndexManagement:1] 2016-09-27 08:22:56,726 CassandraDaemon.java:217 - Exception in thread Thread[SecondaryIndexManagement:1,5,main]
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at org.apache.cassandra.utils.Throwables.maybeFail(Throwables.java:50) ~[apache-cassandra-3.7.jar:3.7]
        at org.apache.cassandra.utils.FBUtilities.waitOnFutures(FBUtilities.java:372) ~[apache-cassandra-3.7.jar:3.7]
        at org.apache.cassandra.index.SecondaryIndexManager.buildIndexesBlocking(SecondaryIndexManager.java:375) ~[apache-cassandra-3.7.jar:3.7]
        at org.apache.cassandra.index.SecondaryIndexManager.buildIndexBlocking(SecondaryIndexManager.java:276) ~[apache-cassandra-3.7.jar:3.7]
        at com.stratio.cassandra.lucene.Index.lambda$getInitializationTask$0(Index.java:136) ~[cassandra-lucene-index-plugin-3.7.3-RC1-SNAPSHOT.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_101]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_101]
        at org.apache.cassandra.utils.FBUtilities.waitOnFutures(FBUtilities.java:365) ~[apache-cassandra-3.7.jar:3.7]
        ... 7 common frames omitted
Caused by: java.lang.OutOfMemoryError: Java heap space
ERROR [PERIODIC-COMMIT-LOG-SYNCER] 2016-09-27 08:22:56,726 JVMStabilityInspector.java:82 - Exiting due to error while processing commit log during initialization.
java.lang.OutOfMemoryError: Java heap space
        at java.util.jar.Manifest$FastInputStream.<init>(Manifest.java:332) ~[na:1.8.0_101]
        at java.util.jar.Manifest$FastInputStream.<init>(Manifest.java:327) ~[na:1.8.0_101]
        at java.util.jar.Manifest.read(Manifest.java:195) ~[na:1.8.0_101]
        at java.util.jar.Manifest.<init>(Manifest.java:69) ~[na:1.8.0_101]
        at java.util.jar.JarFile.getManifestFromReference(JarFile.java:199) ~[na:1.8.0_101]
        at java.util.jar.JarFile.getManifest(JarFile.java:180) ~[na:1.8.0_101]
        at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:944) ~[na:1.8.0_101]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:450) ~[na:1.8.0_101]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_101]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_101]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_101]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_101]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_101]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_101]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_101]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_101]
        at org.apache.cassandra.db.commitlog.AbstractCommitLogService$1.run(AbstractCommitLogService.java:119) ~[apache-cassandra-3.7.jar:3.7]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
```

I had set in the cassandra-env.sh the following values:
MAX_HEAP_SIZE="4G"
HEAP_NEWSIZE="1024M"

All the nodes have 32GB RAM

Any help? Thanks!

**Comment by ealonsodb** [comment]
Hi @drudkhsg:

In order to help you we need some info:
- cassandra-lucene-index versions 
- cassandra upgrade procedure you have followed. 
Have you upgraded sstables before and after cassandra upgrade?

**Comment by drudkhsg** [comment]
Hi @ealonsodb 

I am using [branch 3.7](https://github.com/Stratio/cassandra-lucene-index/tree/branch-3.7) of cassandra-lucene-index and upgrade procedure was followed to the letter from [DataStax](https://docs.datastax.com/en/latest-upgrade/upgrade/cassandra/upgrdCassandraDetails.html).

There are other column-families that have lucene-indexes created successfully without problem.

However, this column-family uses
`{ type : "text", analyzer : "org.apache.lucene.analysis.core.WhitespaceAnalyzer" }`
for one of its columns.
I suspect this is the cause.

**Comment by ealonsodb** [comment]
Hi: 
Can you show us keyspace, table and index creation sentence and some inserts? I will try to reproduce it.

**Comment by drudkhsg** [comment]
Keyspace:

`CREATE KEYSPACE math WITH
REPLICATION = '{'DC1': '3', 'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy'}';`

DC1 has 6 nodes.

Table:

`CREATE math.equations (
topic TEXT, article TEXT, description TEXT, equation TEXT, mathml TEXT, lucene TEXT, PRIMARY KEY (topic, article, equation))
WITH CLUSTERING ORDER BY (article, equation)
AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.2
    AND speculative_retry = '99PERCENTILE';`

Lucene:

`CREATE CUSTOM INDEX ON math.equations (lucene) USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = { 'refresh_seconds' : '1', 'schema' : '{ fields : {
	article : { type : "text", analyzer : "org.apache.lucene.analysis.standard.StandardAnalyzer" },
	equation : { type : "text", analyzer : "org.apache.lucene.analysis.core.WhitespaceAnalyzer" },
	paragraph : { type : "text", analyzer : "org.apache.lucene.analysis.standard.StandardAnalyzer" }
}}'};`

I don't know how to share some inserts because the table has more than 1.8 million rows. The equation column contains LaTeX formulas and they can be huge.

Please let me know how can I help.
Thanks!

**Comment by drudkhsg** [comment]
Keyspace:

`CREATE KEYSPACE math WITH REPLICATION = { 'DC1' : '3', 'class' : 'org.apache.cassandra.locator.NetworkTopologyStrategy' };`

DC1 has 6 nodes.

Table:

`CREATE TABLE math.equations (topic TEXT, equation TEXT, article TEXT, lucene TEXT, description TEXT, PRIMARY KEY (topic, equation, article)) WITH CLUSTERING ORDER BY (equation ASC, article ASC) AND bloom_filter_fp_chance = 0.01 AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'} AND comment = '' AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'} AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'} AND crc_check_chance = 1.0 AND dclocal_read_repair_chance = 0.1 AND default_time_to_live = 0 AND gc_grace_seconds = 864000 AND max_index_interval = 2048 AND memtable_flush_period_in_ms = 0 AND min_index_interval = 128 AND read_repair_chance = 0.2 AND speculative_retry = '99PERCENTILE';`

Lucene:

`CREATE CUSTOM INDEX ON math.equations (lucene) USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = { 'refresh_seconds' : '1', 'schema' : '{ fields : { article : { type : "text", analyzer : "org.apache.lucene.analysis.standard.StandardAnalyzer" }, equation : { type : "text", analyzer : "org.apache.lucene.analysis.core.WhitespaceAnalyzer" }, description : { type : "text", analyzer : "org.apache.lucene.analysis.standard.StandardAnalyzer" } }}'};`

I don't know how to share some inserts because the table has more than 1.8 million rows. The equation column contains LaTeX formulas and they can be huge.

Please let me know how can I help.
Thanks!

**Comment by ealonsodb** [comment]
Hi @drudkhsg: 

According to [Tuning java resources](http://docs.datastax.com/en/cassandra/3.x/cassandra/operations/opsTuneJVM.html) The MAX_HEAP_SIZE for your machine ram amount is 8GB. 

If you dont set neither MAX_HEAP_SIZE nor HEAP_NEWSIZE , [cassandra-env.sh](https://github.com/apache/cassandra/blob/cassandra-3.7/conf/cassandra-env.sh#L17) will calculate this for you. Try this please.

**Comment by adelapena** [comment]
You can also turn off asynchronous parallel indexing to save some memory:
```
CREATE CUSTOM INDEX ON math.equations (lucene) USING 'com.stratio.cassandra.lucene.Index' 
WITH OPTIONS = { 
   'indexing_threads' : '0',
    'refresh_seconds' : '1', 
    'schema' : '{ 
        fields : { 
            article : { type : "text", analyzer : "org.apache.lucene.analysis.standard.StandardAnalyzer" },
            equation : { type : "text", analyzer : "org.apache.lucene.analysis.core.WhitespaceAnalyzer" }, 
            description : { type : "text", analyzer : "org.apache.lucene.analysis.standard.StandardAnalyzer" } 
        }
    }'
};
```

**Comment by drudkhsg** [comment]
Hi @ealonsodb I did not set MAX_HEAP_SIZE and HEAP_NEWSIZE in the beginning, when it threw the error, and so I thought setting them with values might help. I shall remove them.

Thanks!

**Comment by drudkhsg** [comment]
Hi @adelapena thank you for suggesting, I will give that a try.

**Comment by drudkhsg** [comment]
Cassandra would not go to normal state because it truncates the secondary index and re-issues the create index statement on start. I had to physically delete the files from the keyspace to get them up and running, and repopulate the table.

I have removed the settings for MAX_HEAP_SIZE and HEAP_NEWSIZE.

Then, I recreates the index suggested by @adelapena with options `'indexing_threads' : '0'` and I'm still getting the same error.

Should I create the table and index first before repopulating the table? So, we know which row is causing the error?

**Comment by adelapena** [comment]
Hi @drudkhsg ,

Creating the index before populating the table seems a good idea.

It would also be interesting to detect the largest column and/or the largest partition, which are the most suitable for reproducing the issue.

Also, if you can privately share the data we could try to reproduce the problem.
