### ISSUE TITLE
Repairing Cassandra always fails

### ISSUE THREAD

**Issue by evildecay** [Stratio/cassandra-lucene-index#234]
### Environment
- Cassandra version: 3.9
- Cassandra lucene index: 3.9
- The number of clusters: 4
- The data size of each machine: 10GB
- The data is large patition

### Error
```
ERROR [Lucene Merge Thread #13590] 2016-11-10 21:28:50,203 CassandraDaemon.java:226 - Exception in thread Thread[Lucene Merge Thread #13590,5,main]
org.apache.lucene.index.MergePolicy$MergeException: org.apache.lucene.store.AlreadyClosedException: refusing to delete any files: this IndexWriter hit an unrecoverable exception
	at org.apache.lucene.index.ConcurrentMergeScheduler.handleMergeException(ConcurrentMergeScheduler.java:668) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:648) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
Caused by: org.apache.lucene.store.AlreadyClosedException: refusing to delete any files: this IndexWriter hit an unrecoverable exception
	at org.apache.lucene.index.IndexFileDeleter.ensureOpen(IndexFileDeleter.java:343) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.IndexFileDeleter.deleteFile(IndexFileDeleter.java:727) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.IndexFileDeleter.deletePendingFiles(IndexFileDeleter.java:516) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.IndexFileDeleter.deleteNewFiles(IndexFileDeleter.java:719) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.IndexWriter.deleteNewFiles(IndexWriter.java:4679) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4153) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3655) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:588) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3308) ~[na:1.8.0_102]
	at org.apache.lucene.index.SortingLeafReader$SortingPostingsEnum.<init>(SortingLeafReader.java:624) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.SortingLeafReader$SortingTermsEnum.postings(SortingLeafReader.java:155) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.MultiTermsEnum.postings(MultiTermsEnum.java:359) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.MappedMultiFields$MappedMultiTermsEnum.postings(MappedMultiFields.java:127) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.codecs.PushPostingsWriterBase.writeTerm(PushPostingsWriterBase.java:122) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter$TermsWriter.write(BlockTreeTermsWriter.java:1041) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter.write(BlockTreeTermsWriter.java:456) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsWriter.write(PerFieldPostingsFormat.java:198) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.codecs.FieldsConsumer.merge(FieldsConsumer.java:105) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.SegmentMerger.mergeTerms(SegmentMerger.java:193) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:95) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4075) ~[cassandra-lucene-index-plugin-3.9.0-RELEASE.jar:na]
	... 3 common frames omitted
ERROR [Thread-6] 2016-11-10 21:28:50,204 CassandraDaemon.java:226 - Exception in thread Thread[Thread-6,5,main]
org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
```

Setting the synchronization thread failed, and setting the asynchronous thread failed.
Where is the problem?. Thank you!

**Comment by ealonsodb** [comment]
Hi @evildecay: 


There is no cassandra-lucene-index version 3.9. There are versions like 3.9.0 and 3.9.1. Indeed you are using 3.9.0-RELEASE which was a publishing error. Please use either 3.9.0 or 3.9.1 instead. 

You are using a cluster with 4 nodes, aren't you?

When you run `nodetool repair`, nodes start sharing data between them. What you are experiencing is that one node does not have enough Java heap memory to complete the task. 

Ultra-wide partitions in Cassandra are a common antipattern that usually leads to OOM errors. Could it be you case? Can you run `nodetool cfhistograms` over your table in order to get the maximum partition sizes? 

Does increasing the Cassandra Java heap size solve your problem?

**Comment by evildecay** [comment]
Hi @ealonsodb 

Has tried to increase the java heap, but still failed. 

Our analysis is a large partition and lucene principle has a relationship, so look for the lucene official website.
The root cause of the problem may be found on the Lucene official website. 
[https://issues.apache.org/jira/browse/LUCENE-2376](url)

Want to confirm whether this is the reason. Thank you!

**Comment by adelapena** [comment]
[LUCENE-2376](https://issues.apache.org/jira/browse/LUCENE-2376) was targeted to Lucene 2.9.1, which is quite old. Indeed, the thread has been inactive for more than six years, until it was closed one year ago.

How many columns and rows has your large partition?

**Comment by evildecay** [comment]
Hi @adelapena

This is 3 to 4 weeks after the size
```
Percentile  SSTables     Write Latency      Read Latency    Partition Size        Cell Count
                              (micros)          (micros)           (bytes)
50%             8.00            219.34         223875.79           1131752             29521
75%             8.00            263.21         223875.79          17436917           1131752
95%             8.00            315.85         223875.79          36157190           2346799
98%             8.00            315.85         322381.14          36157190           2346799
99%             8.00            379.02         322381.14          36157190           2346799
Min             8.00            152.32            454.83               125                 3
Max             8.00          36157.19         322381.14         557074610          30130992
```

**Comment by adelapena** [comment]
Hi @evildecay,

As you can read [here](http://docs.datastax.com/en/landing_page/doc/landing_page/planning/planningPartitionSize.html):

- Each application will have different efficiency parameters, but a good rule of thumb is to keep the maximum number of rows below 100,000 items and the disk size under 100 MB.

Your rows size seems to be significantly over the recommended limits, which is prone to produce both performance problems and OOM errors, independently of the indexes. As Robbie Strickland says [in this presentation](http://www.slideshare.net/rastrick/lambda-at-weather-scale-cassandra-summit-2015/35), it only takes a single ultra-wide partition to ruin your day...
I think you should review your data model to avoid too large partitions and, then, try to build the indexes.

I hope that helps,

**Comment by evildecay** [comment]
Hi @adelapena 

Yes, we are the same idea. We will divide the data by day. Communicate with you to further confirm this issue. 

Thank you very much for your help.
