### ISSUE TITLE
Cassandra 3.0.9 cannot start when using lucene index 3.0.9.2

### ISSUE THREAD

**Issue by jeanloesch** [Stratio/cassandra-lucene-index#254]
Good morning,

I use Cassandra v3.0.9 under CentOS release 6.6.
I download the jar file cassandra-lucene-index-plugin-3.0.9.2.jar and put into the /opt/cassandra/lib directory. After executing start-cassandra, I got this error in the log and cassandra refuses to start 👍 

```
ERROR [Lucene Merge Thread #0] 2016-12-23 09:17:42,776 CassandraDaemon.java:205 - Exception in thread Thread[Lucene Merge Thread #0,5,main]
org.apache.lucene.index.MergePolicy$MergeException: java.lang.NullPointerException
        at org.apache.lucene.index.ConcurrentMergeScheduler.handleMergeException(ConcurrentMergeScheduler.java:668) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:648) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
Caused by: java.lang.NullPointerException: null
        at com.stratio.cassandra.lucene.util.ByteBufferUtils$.byteBuffer(ByteBufferUtils.scala:115) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at com.stratio.cassandra.lucene.mapping.PartitionSort$$anonfun$$lessinit$greater$1$$anon$1.compareValues(PartitionMapper.scala:159) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at org.apache.lucene.search.FieldComparator$TermValComparator.compareBottom(FieldComparator.java:910) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at org.apache.lucene.index.Sorter$2.compare(Sorter.java:231) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at org.apache.lucene.index.Sorter$DocValueSorter.compare(Sorter.java:106) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at org.apache.lucene.util.Sorter.binarySort(Sorter.java:188) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at org.apache.lucene.util.TimSorter.nextRun(TimSorter.java:120) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at org.apache.lucene.util.TimSorter.sort(TimSorter.java:201) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at org.apache.lucene.index.Sorter.sort(Sorter.java:160) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at org.apache.lucene.index.Sorter.sort(Sorter.java:242) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at org.apache.lucene.index.SortingMergePolicy$SortingOneMerge.getMergeReaders(SortingMergePolicy.java:105) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4064) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3655) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:588) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626) ~[cassandra-lucene-index-plugin-3.0.9.2.jar:na]
```

What is going wrong ? I got the same error with cassandra-lucene-index-plugin-3.0.9.0.jar.
Could you please help ?

Regards.

**Comment by adelapena** [comment]
Hi,

Could you please show both the table and the index creation schema?

Did you have any previous version of the index running?

**Comment by jeanloesch** [comment]
Hi,

I am not creating an index. In fact, my Cassandra cluster has 6 nodes and the version of Cassandra used is 3.0.8. In this version I use the pluging cassandra-lucene-index-plugin-3.0.8.1.jar and there is no problem.
Now I want to upgrade my cluster to Cassandra 3.0.9 using the pluging cassandra-lucene-index-plugin-3.0.9.2.jar. On the first node to upgrade, I stop Cassandra 3.0.8, delete files in /opt/cassandra and install 3.0.9 into this directory.
Then I execute start-cassandra and the error appears.

**Comment by ealonsodb** [comment]
Hi @jeanloesch: 

Please correct me if i am not. 

You have a 6 nodes cluster with cassandra 3.0.8 and cassandra-lucene-index 3.0.8.1 and want to upgrade to cassandra 3.0.9 and cassandra-lucene-index 3.0.9.2. 

Have you read the [upgrade](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst#upgrade) instructions?

The problem is that 3.0.8.1 lucene file structure are not compatible with 3.0.9.2, so you must reindex your tables. 

The process is such as:

1.- Drop every index with old version
2.- Upgrade cassandra following their [instructions](https://docs.datastax.com/en/upgrade/doc/upgrade/cassandra/upgrdCassandraDetails.html)
3.- Copy cassandra-lucene-index to lib directory 
4.- Start new cluster and create custom index again

Hope this helps
Regards

**Comment by jeanloesch** [comment]
Hi Eduardo,

I wasn't aware of the upgrade instructions. Now I know how to find it.
I will try to upgrade with the steps you mentioned.

Thank you very much.

Regards.

**Comment by ealonsodb** [comment]
Hi @jeanloesch: 
Did my answer work for you? Could you please close this issue?

**Comment by jeanloesch** [comment]
Hi Alonso,

Yes, It really worked for me. Excuse me because I forgot to close the case.
Thank you very much for your precious help.

Regards.

**Comment by ealonsodb** [comment]
Thanks @jeanloesch

**Comment by ealonsodb** [comment]
Hi @ajmalsha: 

You can read in [doc](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst#installation) that cassandra-lucene-index version for casandra 3.0.12 should be 3.0.12.X but no-one is generatred yet. We are preparing it.

Please don't comment in closed issues, open a new one.
