### ISSUE TITLE
Cassandra fails during startup after reboot

### ISSUE THREAD

**Issue by sergeydobrodey** [Stratio/cassandra-lucene-index#255]
Environment:
Cassandra 3.9
Lucene index plugin: 3.9.5
Table is quite simple. Only gc_grace_seconds  is changed to 18000 and index refresh interval changed to  5. Oldest events are deleted periodically.
Table schema:
```sql
CREATE TABLE kx_data.archive_events (
    channel bigint,
    start_time timestamp,
    id bigint,
    alarm boolean,        
    end_time timestamp,
    level int,    
    params text,    
    snapshots list<text>,        
    tags list<text>,
    topic text,
    PRIMARY KEY (channel, start_time, id)
) WITH CLUSTERING ORDER BY (start_time ASC, id ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 1800
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX lucene_index ON kx_data.archive_events () USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {'refresh_seconds': '5', 'schema': '{
                                    fields : {
                                        alarm : { type : "boolean", validated : true, column : "alarm" },
                                        topic : { type : "text",    validated : true, column : "topic" },
                                        tags  : { type : "text",    validated : true, column : "tags"  },
                                        level : { type : "integer",     validated : true, column : "level"}
                                    }
                                }'};
```

````java
ERROR 15:08:27 Exception encountered during startup
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.cassandra.db.rows.RangeTombstoneBoundMarker cannot be cast to org.apache.cassandra.db.rows.Row for ks: kx_data, table: archive_events
        at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:403) ~[main/:na]
        at org.apache.cassandra.db.commitlog.CommitLogReplayer.handleMutation(CommitLogReplayer.java:386) ~[main/:na]
        at org.apache.cassandra.db.commitlog.CommitLogReader.readMutation(CommitLogReader.java:424) ~[main/:na]
        at org.apache.cassandra.db.commitlog.CommitLogReader.readSection(CommitLogReader.java:343) ~[main/:na]
        at org.apache.cassandra.db.commitlog.CommitLogReader.readCommitLogSegment(CommitLogReader.java:202) ~[main/:na]
        at org.apache.cassandra.db.commitlog.CommitLogReader.readAllFiles(CommitLogReader.java:85) ~[main/:na]
        at org.apache.cassandra.db.commitlog.CommitLogReplayer.replayFiles(CommitLogReplayer.java:135) ~[main/:na]
        at org.apache.cassandra.db.commitlog.CommitLog.recoverFiles(CommitLog.java:187) ~[main/:na]
        at org.apache.cassandra.db.commitlog.CommitLog.recoverSegmentsOnDisk(CommitLog.java:167) ~[main/:na]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:323) [main/:na]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601) [main/:na]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:730) [main/:na]
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.cassandra.db.rows.RangeTombstoneBoundMarker cannot be cast to org.apache.cassandra.db.rows.Row for ks: kx_data, table: archive_events
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.get(AbstractLocalAwareExecutorService.java:200) ~[main/:na]
        at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:399) ~[main/:na]
        ... 11 common frames omitted
Caused by: java.lang.RuntimeException: org.apache.cassandra.db.rows.RangeTombstoneBoundMarker cannot be cast to org.apache.cassandra.db.rows.Row for ks: kx_data, table: archive_events
        at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1316) ~[main/:na]
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:526) ~[main/:na]
        at org.apache.cassandra.db.Keyspace.applyFromCommitLog(Keyspace.java:406) ~[main/:na]
        at org.apache.cassandra.db.commitlog.CommitLogReplayer$MutationInitiator$1.runMayThrow(CommitLogReplayer.java:224) ~[main/:na]
        at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) ~[main/:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_102]
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:164) ~[main/:na]
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:109) ~[main/:na]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
Caused by: java.lang.ClassCastException: org.apache.cassandra.db.rows.RangeTombstoneBoundMarker cannot be cast to org.apache.cassandra.db.rows.Row
        at com.stratio.cassandra.lucene.IndexWriterWide.$anonfun$finish$1(IndexWriterWide.scala:80) ~[cassandra-lucene-index-plugin-3.9.5.jar:na]
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:448) ~[cassandra-lucene-index-plugin-3.9.5.jar:na]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:932) ~[cassandra-lucene-index-plugin-3.9.5.jar:na]
        at com.stratio.cassandra.lucene.IndexWriterWide.finish(IndexWriterWide.scala:81) ~[cassandra-lucene-index-plugin-3.9.5.jar:na]
        at org.apache.cassandra.index.SecondaryIndexManager$WriteTimeTransaction.commit(SecondaryIndexManager.java:856) ~[main/:na]
        at org.apache.cassandra.db.partitions.AtomicBTreePartition.addAllWithSizeDelta(AtomicBTreePartition.java:181) ~[main/:na]
        at org.apache.cassandra.db.Memtable.put(Memtable.java:258) ~[main/:na]
        at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1303) ~[main/:na]
        ... 8 common frames omitted
```

**Comment by ealonsodb** [comment]
Hi @sergeydobrodey : 

It is a bug. 
I have commited a [hotfix_255](https://github.com/Stratio/cassandra-lucene-index/tree/hotfix/issue_255) branch. 

Regards

**Comment by sergeydobrodey** [comment]
Thanks for the quick fix
