### ISSUE TITLE
Plugin not working on Cassandra 3.10, previously worked on 3.7

### ISSUE THREAD

**Issue by didip** [Stratio/cassandra-lucene-index#308]
Cassandra: 3.10
Plugin: cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar
JVM: Azul Zing: zing-jdk1.8.0-16.10.0.0-7

We are trying to upgrade from
Cassandra: 3.7
Plugin: 3.7.3
JVM: Azul Zing: zing-jdk1.8.0-16.10.0.0-7

Do I need newer JDK? Which version of Scala works with which version of JDK?

The output on cassandra.log
```
Exception (java.lang.RuntimeException) encountered during startup: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:432)
	at org.apache.cassandra.index.SecondaryIndexManager.createIndex(SecondaryIndexManager.java:166)
	at org.apache.cassandra.index.SecondaryIndexManager.addIndex(SecondaryIndexManager.java:192)
	at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:446)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:618)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:592)
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:583)
	at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:409)
	at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:322)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:127)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:104)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:293)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:735)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:428)
	... 13 more
Caused by: java.lang.VerifyError: Uninitialized object exists on backward branch 209 
Exception Details:
  Location:
    scala/collection/immutable/HashMap$HashTrieMap.split()Lscala/collection/immutable/Seq; @249: goto
  Reason:
     Error exists in the bytecode 
  Bytecode:
    0000000: 2ab6 0057 04a0 001e b200 afb2 00b4 04bd 
    0000010: 0002 5903 2a53 c000 b6b6 00ba b600 bec0 
    0000020: 00c0 b02a b600 31b8 003b 3c1b 04a4 015e 
    0000030: 1b05 6c3d 2a1b 056c 2ab6 0031 b700 c23e 
    0000040: 2ab6 0031 021d 787e 3604 2ab6 0031 0210 
    0000050: 201d 647c 7e36 05bb 0014 59b2 00b4 2ab6 
    0000060: 0033 c000 b6b6 00c6 b700 c91c b600 cd3a 
    0000070: 0619 06c6 001a 1906 b600 d1c0 007d 3a07 
    0000080: 1906 b600 d4c0 007d 3a08 a700 0dbb 00d6 
    0000090: 5919 06b7 00d9 bf19 073a 0919 083a 0abb 
    00000a0: 0002 5915 0419 09bb 0014 59b2 00b4 1909 
    00000b0: c000 b6b6 00c6 b700 c903 b800 df3a 0e3a 
    00000c0: 0d03 190d b900 e301 0019 0e3a 1136 1036 
    00000d0: 0f15 0f15 109f 0027 150f 0460 1510 190d 
    00000e0: 150f b900 e602 00c0 0005 3a17 1911 1917 
    00000f0: b800 ea3a 1136 1036 0fa7 ffd8 1911 b800 
    0000100: eeb7 005c 3a0b bb00 0259 1505 190a bb00 
    0000110: 1459 b200 b419 0ac0 00b6 b600 c6b7 00c9 
    0000120: 03b8 00df 3a13 3a12 0319 12b9 00e3 0100 
    0000130: 1913 3a16 3615 3614 1514 1515 9f00 2715 
    0000140: 1404 6015 1519 1215 14b9 00e6 0200 c000 
    0000150: 053a 1819 1619 18b8 00f1 3a16 3615 3614 
    0000160: a7ff d819 16b8 00ee b700 5c3a 0cb2 00f6 
    0000170: b200 b405 bd00 0259 0319 0b53 5904 190c 
    0000180: 53c0 00b6 b600 bab6 00f9 b02a b600 3303 
    0000190: 32b6 00fb b0                            
  Stackmap Table:
    same_frame(@35) 
    full_frame(@141,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105]},{}) 
    append_frame(@151,Object[#125],Object[#125]) 
    full_frame(@209,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Top,Top,Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#125]}) 
    full_frame(@252,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Top,Top,Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#125]}) 
    full_frame(@312,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Object[#2],Top,Object[#20],Object[#55],Integer,Integer,Object[#103],Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#125]}) 
    full_frame(@355,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Object[#2],Top,Object[#20],Object[#55],Integer,Integer,Object[#103],Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#125]}) 
    full_frame(@395,{Object[#2],Integer},{}) 

	at scala.collection.immutable.HashMap$.scala$collection$immutable$HashMap$$makeHashTrieMap(HashMap.scala:179)
	at scala.collection.immutable.HashMap$HashMap1.updated0(HashMap.scala:211)
	at scala.collection.immutable.HashMap.$plus(HashMap.scala:59)
	at scala.collection.immutable.HashMap.$plus(HashMap.scala:62)
	at scala.collection.immutable.Map$Map4.updated(Map.scala:201)
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:202)
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:180)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:29)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:25)
	at scala.collection.TraversableOnce.$anonfun$toMap$1(TraversableOnce.scala:317)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:932)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.toMap(TraversableOnce.scala:316)
	at scala.collection.TraversableOnce.toMap$(TraversableOnce.scala:314)
	at scala.collection.AbstractTraversable.toMap(Traversable.scala:104)
	at com.stratio.cassandra.lucene.IndexOptions.<init>(IndexOptions.scala:39)
	at com.stratio.cassandra.lucene.IndexService.<init>(IndexService.scala:58)
	at com.stratio.cassandra.lucene.IndexServiceWide.<init>(IndexServiceWide.scala:43)
	at com.stratio.cassandra.lucene.IndexService$.build(IndexService.scala:436)
	at com.stratio.cassandra.lucene.Index.liftedTree1$1(Index.scala:55)
	at com.stratio.cassandra.lucene.Index.<init>(Index.scala:55)
	... 18 more
ERROR 2017-03-28 18:19:11,809 [main] [CassandraDaemon] [line 752] Exception encountered during startup 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:432) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.index.SecondaryIndexManager.createIndex(SecondaryIndexManager.java:166) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.index.SecondaryIndexManager.addIndex(SecondaryIndexManager.java:192) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:446) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:618) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:592) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:583) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:409) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:322) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:127) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:104) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:293) [apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601) [apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:735) [apache-cassandra-3.10.jar:3.10]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0-zing_16.10.0.0]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0-zing_16.10.0.0]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0-zing_16.10.0.0]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0-zing_16.10.0.0]
	at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:428) ~[apache-cassandra-3.10.jar:3.10]
	... 13 common frames omitted
Caused by: java.lang.VerifyError: Uninitialized object exists on backward branch 209 
Exception Details:
  Location:
    scala/collection/immutable/HashMap$HashTrieMap.split()Lscala/collection/immutable/Seq; @249: goto
  Reason:
     Error exists in the bytecode 
  Bytecode:
    0000000: 2ab6 0057 04a0 001e b200 afb2 00b4 04bd 
    0000010: 0002 5903 2a53 c000 b6b6 00ba b600 bec0 
    0000020: 00c0 b02a b600 31b8 003b 3c1b 04a4 015e 
    0000030: 1b05 6c3d 2a1b 056c 2ab6 0031 b700 c23e 
    0000040: 2ab6 0031 021d 787e 3604 2ab6 0031 0210 
    0000050: 201d 647c 7e36 05bb 0014 59b2 00b4 2ab6 
    0000060: 0033 c000 b6b6 00c6 b700 c91c b600 cd3a 
    0000070: 0619 06c6 001a 1906 b600 d1c0 007d 3a07 
    0000080: 1906 b600 d4c0 007d 3a08 a700 0dbb 00d6 
    0000090: 5919 06b7 00d9 bf19 073a 0919 083a 0abb 
    00000a0: 0002 5915 0419 09bb 0014 59b2 00b4 1909 
    00000b0: c000 b6b6 00c6 b700 c903 b800 df3a 0e3a 
    00000c0: 0d03 190d b900 e301 0019 0e3a 1136 1036 
    00000d0: 0f15 0f15 109f 0027 150f 0460 1510 190d 
    00000e0: 150f b900 e602 00c0 0005 3a17 1911 1917 
    00000f0: b800 ea3a 1136 1036 0fa7 ffd8 1911 b800 
    0000100: eeb7 005c 3a0b bb00 0259 1505 190a bb00 
    0000110: 1459 b200 b419 0ac0 00b6 b600 c6b7 00c9 
    0000120: 03b8 00df 3a13 3a12 0319 12b9 00e3 0100 
    0000130: 1913 3a16 3615 3614 1514 1515 9f00 2715 
    0000140: 1404 6015 1519 1215 14b9 00e6 0200 c000 
    0000150: 053a 1819 1619 18b8 00f1 3a16 3615 3614 
    0000160: a7ff d819 16b8 00ee b700 5c3a 0cb2 00f6 
    0000170: b200 b405 bd00 0259 0319 0b53 5904 190c 
    0000180: 53c0 00b6 b600 bab6 00f9 b02a b600 3303 
    0000190: 32b6 00fb b0                            
  Stackmap Table:
    same_frame(@35) 
    full_frame(@141,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105]},{}) 
    append_frame(@151,Object[#125],Object[#125]) 
    full_frame(@209,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Top,Top,Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#125]}) 
    full_frame(@252,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Top,Top,Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#125]}) 
    full_frame(@312,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Object[#2],Top,Object[#20],Object[#55],Integer,Integer,Object[#103],Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#125]}) 
    full_frame(@355,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Object[#2],Top,Object[#20],Object[#55],Integer,Integer,Object[#103],Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#125]}) 
    full_frame(@395,{Object[#2],Integer},{}) 

	at scala.collection.immutable.HashMap$.scala$collection$immutable$HashMap$$makeHashTrieMap(HashMap.scala:179) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.immutable.HashMap$HashMap1.updated0(HashMap.scala:211) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.immutable.HashMap.$plus(HashMap.scala:59) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.immutable.HashMap.$plus(HashMap.scala:62) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.immutable.Map$Map4.updated(Map.scala:201) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:202) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:180) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:29) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:25) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.TraversableOnce.$anonfun$toMap$1(TraversableOnce.scala:317) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:932) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.TraversableOnce.toMap(TraversableOnce.scala:316) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.TraversableOnce.toMap$(TraversableOnce.scala:314) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.AbstractTraversable.toMap(Traversable.scala:104) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at com.stratio.cassandra.lucene.IndexOptions.<init>(IndexOptions.scala:39) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at com.stratio.cassandra.lucene.IndexService.<init>(IndexService.scala:58) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at com.stratio.cassandra.lucene.IndexServiceWide.<init>(IndexServiceWide.scala:43) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at com.stratio.cassandra.lucene.IndexService$.build(IndexService.scala:436) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at com.stratio.cassandra.lucene.Index.liftedTree1$1(Index.scala:55) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at com.stratio.cassandra.lucene.Index.<init>(Index.scala:55) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	... 18 common frames omitted
ERROR 2017-03-28 18:19:11,809 [main] [CassandraDaemon] [line 752] Exception encountered during startup 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:432) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.index.SecondaryIndexManager.createIndex(SecondaryIndexManager.java:166) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.index.SecondaryIndexManager.addIndex(SecondaryIndexManager.java:192) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:446) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:618) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:592) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:583) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:409) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:322) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:127) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:104) ~[apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:293) [apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601) [apache-cassandra-3.10.jar:3.10]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:735) [apache-cassandra-3.10.jar:3.10]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0-zing_16.10.0.0]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0-zing_16.10.0.0]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0-zing_16.10.0.0]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0-zing_16.10.0.0]
	at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:428) ~[apache-cassandra-3.10.jar:3.10]
	... 13 common frames omitted
Caused by: java.lang.VerifyError: Uninitialized object exists on backward branch 209 
Exception Details:
  Location:
    scala/collection/immutable/HashMap$HashTrieMap.split()Lscala/collection/immutable/Seq; @249: goto
  Reason:
     Error exists in the bytecode 
  Bytecode:
    0000000: 2ab6 0057 04a0 001e b200 afb2 00b4 04bd 
    0000010: 0002 5903 2a53 c000 b6b6 00ba b600 bec0 
    0000020: 00c0 b02a b600 31b8 003b 3c1b 04a4 015e 
    0000030: 1b05 6c3d 2a1b 056c 2ab6 0031 b700 c23e 
    0000040: 2ab6 0031 021d 787e 3604 2ab6 0031 0210 
    0000050: 201d 647c 7e36 05bb 0014 59b2 00b4 2ab6 
    0000060: 0033 c000 b6b6 00c6 b700 c91c b600 cd3a 
    0000070: 0619 06c6 001a 1906 b600 d1c0 007d 3a07 
    0000080: 1906 b600 d4c0 007d 3a08 a700 0dbb 00d6 
    0000090: 5919 06b7 00d9 bf19 073a 0919 083a 0abb 
    00000a0: 0002 5915 0419 09bb 0014 59b2 00b4 1909 
    00000b0: c000 b6b6 00c6 b700 c903 b800 df3a 0e3a 
    00000c0: 0d03 190d b900 e301 0019 0e3a 1136 1036 
    00000d0: 0f15 0f15 109f 0027 150f 0460 1510 190d 
    00000e0: 150f b900 e602 00c0 0005 3a17 1911 1917 
    00000f0: b800 ea3a 1136 1036 0fa7 ffd8 1911 b800 
    0000100: eeb7 005c 3a0b bb00 0259 1505 190a bb00 
    0000110: 1459 b200 b419 0ac0 00b6 b600 c6b7 00c9 
    0000120: 03b8 00df 3a13 3a12 0319 12b9 00e3 0100 
    0000130: 1913 3a16 3615 3614 1514 1515 9f00 2715 
    0000140: 1404 6015 1519 1215 14b9 00e6 0200 c000 
    0000150: 053a 1819 1619 18b8 00f1 3a16 3615 3614 
    0000160: a7ff d819 16b8 00ee b700 5c3a 0cb2 00f6 
    0000170: b200 b405 bd00 0259 0319 0b53 5904 190c 
    0000180: 53c0 00b6 b600 bab6 00f9 b02a b600 3303 
    0000190: 32b6 00fb b0                            
  Stackmap Table:
    same_frame(@35) 
    full_frame(@141,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105]},{}) 
    append_frame(@151,Object[#125],Object[#125]) 
    full_frame(@209,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Top,Top,Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#125]}) 
    full_frame(@252,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Top,Top,Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#125]}) 
    full_frame(@312,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Object[#2],Top,Object[#20],Object[#55],Integer,Integer,Object[#103],Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#125]}) 
    full_frame(@355,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Object[#2],Top,Object[#20],Object[#55],Integer,Integer,Object[#103],Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#125]}) 
    full_frame(@395,{Object[#2],Integer},{}) 

	at scala.collection.immutable.HashMap$.scala$collection$immutable$HashMap$$makeHashTrieMap(HashMap.scala:179) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.immutable.HashMap$HashMap1.updated0(HashMap.scala:211) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.immutable.HashMap.$plus(HashMap.scala:59) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.immutable.HashMap.$plus(HashMap.scala:62) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.immutable.Map$Map4.updated(Map.scala:201) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:202) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:180) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:29) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:25) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.TraversableOnce.$anonfun$toMap$1(TraversableOnce.scala:317) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:932) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.TraversableOnce.toMap(TraversableOnce.scala:316) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.TraversableOnce.toMap$(TraversableOnce.scala:314) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at scala.collection.AbstractTraversable.toMap(Traversable.scala:104) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at com.stratio.cassandra.lucene.IndexOptions.<init>(IndexOptions.scala:39) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at com.stratio.cassandra.lucene.IndexService.<init>(IndexService.scala:58) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at com.stratio.cassandra.lucene.IndexServiceWide.<init>(IndexServiceWide.scala:43) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at com.stratio.cassandra.lucene.IndexService$.build(IndexService.scala:436) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at com.stratio.cassandra.lucene.Index.liftedTree1$1(Index.scala:55) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	at com.stratio.cassandra.lucene.Index.<init>(Index.scala:55) ~[cassandra-lucene-index-plugin-3.10.0-RC1-SNAPSHOT.jar:na]
	... 18 common frames omitted
```

**Comment by ealonsodb** [comment]
Hi @didip: 

We didn't even know about Azul Zing JDK existence. We think the error is because a bad scala version but not sure.

[cassandra-lucene-index:3.7.3 uses scala 2.10.4](https://github.com/Stratio/cassandra-lucene-index/blob/3.7.3/plugin/pom.xml#L38) but [casandra-lcuene-index:3.10.0-RC1-SNAPSHOT uses scala 2.12.0](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.10/pom.xml#L91)

Hope this helps

**Comment by didip** [comment]
Yes, this confirms my suspicion that Scala got upgraded.

Scala 2.12.x requires higher spec of JDK 1.8 (JDK 1.8.0_111 to be specific) and our Zing is slightly older.

So, I have a question...

Is it possible to compile from source using older Scala for 3.10.0 snapshot (via maven)? It would help me tremendously because I would love to be able to upgrade to 3.10 and still use the plugin. 

It would be awesome if you guys can provide a flag (which Scala to choose and it still defaults to Scala 2.12.0).

Would that be too much to ask?

**Comment by ealonsodb** [comment]
Hi @didip: 
Using scala 2.12 is not a free election, we need some libraries written in scala 2.12. Also, we cannot mantain several versions with several dependencies, we choose one and continue.

I would recommend you to use another azul king jdk version with scala 2.12 included. 

If you want, also you can fork this project, checkout a new branch from branch-3.10, change to scala 2.10.4 and generate your own jar.

Library version are in parent [pom.xml](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.10/pom.xml#L78-L94), modify them and compile until it works.

Hope this helps

**Comment by didip** [comment]
Yeah, that makes total sense.

Thank you for the thoughtful replies. This project is great and works at really high throughput too :)
