### ISSUE TITLE
build failed for branch-3.0.12

### ISSUE THREAD

**Issue by craveica** [Stratio/cassandra-lucene-index#311]
```
Running com.stratio.cassandra.lucene.index.FSIndexTest
Exception in thread "Thread-7" java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/junit4209883561392725031/directory5355714f-b782-451c-9110-1ead962b82d9/_0.cfe
        at org.apache.lucene.search.ControlledRealTimeReopenThread.run(ControlledRealTimeReopenThread.java:247)
Caused by: java.nio.file.NoSuchFileException: /tmp/junit4209883561392725031/directory5355714f-b782-451c-9110-1ead962b82d9/_0.cfe
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:335)
        at org.apache.lucene.store.MMapDirectory.openInput(MMapDirectory.java:244)
        at org.apache.lucene.store.NRTCachingDirectory.openInput(NRTCachingDirectory.java:187)
        at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:109)
        at org.apache.lucene.codecs.lucene50.Lucene50CompoundReader.readEntries(Lucene50CompoundReader.java:105)
        at org.apache.lucene.codecs.lucene50.Lucene50CompoundReader.<init>(Lucene50CompoundReader.java:69)
        at org.apache.lucene.codecs.lucene50.Lucene50CompoundFormat.getCompoundReader(Lucene50CompoundFormat.java:71)
        at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:93)
        at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:65)
        at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:145)
        at org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:197)
        at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:99)
        at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:435)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:286)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:261)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:251)
        at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:137)
        at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:154)
        at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
        at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
        at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
        at org.apache.lucene.search.ControlledRealTimeReopenThread.run(ControlledRealTimeReopenThread.java:245)
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.149 sec <<< FAILURE! - in com.stratio.cassandra.lucene.index.FSIndexTest
CRUD operations(com.stratio.cassandra.lucene.index.FSIndexTest)  Time elapsed: 0.147 sec  <<< FAILURE!
java.lang.AssertionError: Expected 2 documents expected:<2> but was:<0>
        at com.stratio.cassandra.lucene.index.FSIndexTest.$anonfun$new$2(FSIndexTest.scala:90)
        at com.stratio.cassandra.lucene.index.FSIndexTest.$anonfun$new$2$adapted(FSIndexTest.scala:68)
        at com.stratio.cassandra.lucene.index.FSIndexTest.doWithIndex(FSIndexTest.scala:62)
        at com.stratio.cassandra.lucene.index.FSIndexTest.$anonfun$new$1(FSIndexTest.scala:68)

Results :

Failed tests:
  FSIndexTest>FunSuite.run:1560->FunSuite.org$scalatest$FunSuiteLike$$super$run:1560->FunSuite.runTests:1560->FunSuite.runTest:1560->FunSuite.withFixture:1560->$anonfun$new$1:68->doWithIndex:62->$anonfun$new$2$adapted:68->$anonfun$new$2:90 Expected 2 documents expected:<2> but was:<0>
```

**Comment by craveica** [comment]
solved by adding -Djava.io.tmpdir to mvn.
