### ISSUE TITLE
.jar build for 3.0.12.0 release fails unit tests.

### ISSUE THREAD

**Issue by cscicchillo** [Stratio/cassandra-lucene-index#312]
RHEL 6.8 (2.6.31-642.15.1)
Oracle JDK 1.8.0_121
Maven 3.5.0

Generates the following during 'mvn clean package':
Release for 3.10.0 builds clean on same system.

```
Tests run: 25, Failures: 0, Errors: 13, Skipped: 0, Time elapsed: 0.018 sec <<< FAILURE! - in com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest
testSortTimeUUIDsAsNative(com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testSort(UUIDMapperTest.java:303)
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testSortTimeUUIDsAsNative(UUIDMapperTest.java:252)

testIndexedField(com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testIndexedField(UUIDMapperTest.java:139)

testCompareRandomUUID(com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testCompareRandomUUID(UUIDMapperTest.java:211)

testSortTimeUUIDsAsGeneral(com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testSort(UUIDMapperTest.java:303)
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testSortTimeUUIDsAsGeneral(UUIDMapperTest.java:236)

testValueUUIDTimeBased(com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testValueUUIDTimeBased(UUIDMapperTest.java:84)

testValueStringTimeBased(com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testValueStringTimeBased(UUIDMapperTest.java:98)

testCompareTimeUUID(com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testCompareTimeUUID(UUIDMapperTest.java:191)

testSortMixedUUIDs(com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testSort(UUIDMapperTest.java:303)
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testSortMixedUUIDs(UUIDMapperTest.java:295)

testSortRandomUUIDs(com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testSort(UUIDMapperTest.java:303)
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testSortRandomUUIDs(UUIDMapperTest.java:268)

testSortedField(com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testSortedField(UUIDMapperTest.java:150)

testValueStringRandom(com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testValueStringRandom(UUIDMapperTest.java:91)

testValueUUIDRandom(com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testValueUUIDRandom(UUIDMapperTest.java:77)

testCompareDifferentTypes(com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.UUIDMapperTest.testCompareDifferentTypes(UUIDMapperTest.java:171)

Running com.stratio.cassandra.lucene.schema.mapping.IntegerMapperTest
Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in com.stratio.cassandra.lucene.schema.mapping.IntegerMapperTest
Running com.stratio.cassandra.lucene.schema.mapping.DateMapperTest
Tests run: 24, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.015 sec <<< FAILURE! - in com.stratio.cassandra.lucene.schema.mapping.DateMapperTest
testBaseNotTimeUUID(com.stratio.cassandra.lucene.schema.mapping.DateMapperTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<com.stratio.cassandra.lucene.IndexException> but was<java.lang.NoClassDefFoundError>
        at com.stratio.cassandra.lucene.schema.mapping.DateMapperTest.testBaseNotTimeUUID(DateMapperTest.java:185)

testBaseTimeUUID(com.stratio.cassandra.lucene.schema.mapping.DateMapperTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.DateMapperTest.testBaseTimeUUID(DateMapperTest.java:179)

Running com.stratio.cassandra.lucene.schema.mapping.GeoShapeMapperTest
Tests run: 30, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.05 sec - in com.stratio.cassandra.lucene.schema.mapping.GeoShapeMapperTest
Running com.stratio.cassandra.lucene.schema.mapping.StringMapperTest
Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec - in com.stratio.cassandra.lucene.schema.mapping.StringMapperTest
Running com.stratio.cassandra.lucene.schema.mapping.BigDecimalMapperTest
Tests run: 86, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.056 sec - in com.stratio.cassandra.lucene.schema.mapping.BigDecimalMapperTest
Running com.stratio.cassandra.lucene.schema.mapping.GeoPointMapperTest
Tests run: 48, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec - in com.stratio.cassandra.lucene.schema.mapping.GeoPointMapperTest
Running com.stratio.cassandra.lucene.schema.mapping.DoubleMapperTest
Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in com.stratio.cassandra.lucene.schema.mapping.DoubleMapperTest
Running com.stratio.cassandra.lucene.schema.mapping.BitemporalMapperTest
Tests run: 45, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.034 sec <<< FAILURE! - in com.stratio.cassandra.lucene.schema.mapping.BitemporalMapperTest
testReadFieldFromTimeUUIDColumn(com.stratio.cassandra.lucene.schema.mapping.BitemporalMapperTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.BitemporalMapperTest.testReadFieldFromTimeUUIDColumn(BitemporalMapperTest.java:210)

Running com.stratio.cassandra.lucene.schema.mapping.DateRangeMapperTest
Tests run: 26, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.009 sec <<< FAILURE! - in com.stratio.cassandra.lucene.schema.mapping.DateRangeMapperTest
testReadFieldFromTimeUUIDColumn(com.stratio.cassandra.lucene.schema.mapping.DateRangeMapperTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at com.stratio.cassandra.lucene.schema.mapping.DateRangeMapperTest.testReadFieldFromTimeUUIDColumn(DateRangeMapperTest.java:137)

testReadFieldFromRandomUUIDColumn(com.stratio.cassandra.lucene.schema.mapping.DateRangeMapperTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<com.stratio.cassandra.lucene.IndexException> but was<java.lang.NoClassDefFoundError>
        at com.stratio.cassandra.lucene.schema.mapping.DateRangeMapperTest.testReadField(DateRangeMapperTest.java:110)
        at com.stratio.cassandra.lucene.schema.mapping.DateRangeMapperTest.testReadFieldFromRandomUUIDColumn(DateRangeMapperTest.java:143)

Running com.stratio.cassandra.lucene.schema.mapping.FloatMapperTest
Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in com.stratio.cassandra.lucene.schema.mapping.FloatMapperTest
Running com.stratio.cassandra.lucene.schema.mapping.LongMapperTest
Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in com.stratio.cassandra.lucene.schema.mapping.LongMapperTest
Running com.stratio.cassandra.lucene.schema.mapping.TextMapperTest
Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in com.stratio.cassandra.lucene.schema.mapping.TextMapperTest
Running com.stratio.cassandra.lucene.schema.mapping.BigIntegerMapperTest
Tests run: 83, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec - in com.stratio.cassandra.lucene.schema.mapping.BigIntegerMapperTest
Running com.stratio.cassandra.lucene.schema.mapping.BooleanMapperTest
Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in com.stratio.cassandra.lucene.schema.mapping.BooleanMapperTest
Running com.stratio.cassandra.lucene.schema.mapping.InetMapperTest
Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in com.stratio.cassandra.lucene.schema.mapping.InetMapperTest
Running com.stratio.cassandra.lucene.schema.mapping.BlobMapperTest
Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in com.stratio.cassandra.lucene.schema.mapping.BlobMapperTest
Running com.stratio.cassandra.lucene.schema.mapping.MapperTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.stratio.cassandra.lucene.schema.mapping.MapperTest
Running com.stratio.cassandra.lucene.schema.SchemaAnalyzerTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.stratio.cassandra.lucene.schema.SchemaAnalyzerTest
Running com.stratio.cassandra.lucene.schema.analysis.SnowballAnalyzerBuilderTest
Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.065 sec - in com.stratio.cassandra.lucene.schema.analysis.SnowballAnalyzerBuilderTest
Running com.stratio.cassandra.lucene.schema.analysis.StandardStopwordsTest
Tests run: 21, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in com.stratio.cassandra.lucene.schema.analysis.StandardStopwordsTest
Running com.stratio.cassandra.lucene.schema.analysis.StandardAnalyzersTest
Tests run: 43, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.068 sec - in com.stratio.cassandra.lucene.schema.analysis.StandardAnalyzersTest
Running com.stratio.cassandra.lucene.schema.analysis.ClasspathAnalyzerBuilderTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.stratio.cassandra.lucene.schema.analysis.ClasspathAnalyzerBuilderTest
Running com.stratio.cassandra.lucene.schema.SchemaBuilderTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec - in com.stratio.cassandra.lucene.schema.SchemaBuilderTest
Running com.stratio.cassandra.lucene.IndexOptionsTest
Tests run: 44, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.164 sec - in com.stratio.cassandra.lucene.IndexOptionsTest
Running com.stratio.cassandra.lucene.mapping.ColumnsMapperTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.018 sec <<< FAILURE! - in com.stratio.cassandra.lucene.mapping.ColumnsMapperTest
com.stratio.cassandra.lucene.mapping.ColumnsMapperTest  Time elapsed: 0.006 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.cassandra.utils.UUIDGen
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)

Running com.stratio.cassandra.lucene.mapping.TokenMapperTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 sec - in com.stratio.cassandra.lucene.mapping.TokenMapperTest
Running com.stratio.cassandra.lucene.mapping.ClusteringMapperTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec - in com.stratio.cassandra.lucene.mapping.ClusteringMapperTest
Running com.stratio.cassandra.lucene.index.NoIDFSimilarityTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in com.stratio.cassandra.lucene.index.NoIDFSimilarityTest
Running com.stratio.cassandra.lucene.index.FSIndexTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.105 sec - in com.stratio.cassandra.lucene.index.FSIndexTest
Running com.stratio.cassandra.lucene.index.PartitionedIndexTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.54 sec - in com.stratio.cassandra.lucene.index.PartitionedIndexTest


```
Results :

Tests in error:
  DateParserTest.testParseUUID:181 » UnsatisfiedLink org.apache.cassandra.utils....
  BitemporalMapperTest.testReadFieldFromTimeUUIDColumn:210 NoClassDefFound Could...
  DateMapperTest.testBaseNotTimeUUID »  Unexpected exception, expected<com.strat...
  DateMapperTest.testBaseTimeUUID:179 NoClassDefFound Could not initialize class...
  DateRangeMapperTest.testReadFieldFromRandomUUIDColumn »  Unexpected exception,...
  DateRangeMapperTest.testReadFieldFromTimeUUIDColumn:137 NoClassDefFound Could ...
  UUIDMapperTest.testCompareDifferentTypes:171 » NoClassDefFound Could not initi...
  UUIDMapperTest.testCompareRandomUUID:211 » NoClassDefFound Could not initializ...
  UUIDMapperTest.testCompareTimeUUID:191 » NoClassDefFound Could not initialize ...
  UUIDMapperTest.testIndexedField:139 » NoClassDefFound Could not initialize cla...
  UUIDMapperTest.testSortMixedUUIDs:295->testSort:303 » NoClassDefFound Could no...
  UUIDMapperTest.testSortRandomUUIDs:268->testSort:303 » NoClassDefFound Could n...
  UUIDMapperTest.testSortTimeUUIDsAsGeneral:236->testSort:303 » NoClassDefFound ...
  UUIDMapperTest.testSortTimeUUIDsAsNative:252->testSort:303 » NoClassDefFound C...
  UUIDMapperTest.testSortedField:150 » NoClassDefFound Could not initialize clas...
  UUIDMapperTest.testValueStringRandom:91 » NoClassDefFound Could not initialize...
  UUIDMapperTest.testValueStringTimeBased:98 » NoClassDefFound Could not initial...
  UUIDMapperTest.testValueUUIDRandom:77 » NoClassDefFound Could not initialize c...
  UUIDMapperTest.testValueUUIDTimeBased:84 » NoClassDefFound Could not initializ...
  JUnit4Provider.invoke:161->executeTestSet:238->executeWithRerun:274->execute:367 » NoClassDefFound

Tests run: 1223, Failures: 0, Errors: 20, Skipped: 0
```
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Cassandra Lucene index ............................. SUCCESS [  1.055 s]
[INFO] Cassandra Lucene Index builder ..................... SUCCESS [  6.856 s]
[INFO] Cassandra Lucene Index plugin ...................... FAILURE [ 35.883 s]
[INFO] Cassandra Lucene Index distribution ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.125 s
[INFO] Finished at: 2017-04-12T14:49:50Z
[INFO] Final Memory: 55M/391M
```

**Comment by ealonsodb** [comment]
Hi @cscicchillo: 

I have tested this now with tag [3.0.12.0](https://github.com/Stratio/cassandra-lucene-index/tree/3.0.12.0) and works ok(my HEAD is pointing to [f93d9b8afc77e8fcaac8d2d0f116fee8af0c1a1e](https://github.com/Stratio/cassandra-lucene-index/commit/f93d9b8afc77e8fcaac8d2d0f116fee8af0c1a1e)): 

```
git clone http://www.github.com/stratio/cassandra-lucene-index
cd cassandra-lucene-index
git checkout 3.0.12.0
mvn clean package
```

As i see in your logs, you are having problem with cassandra-3.0.12 as a dependency. 
The class [UUIDGen.java:3.0.12](https://github.com/apache/cassandra/blob/cassandra-3.0.12/src/java/org/apache/cassandra/utils/UUIDGen.java) is in cassandra 3.0.12 and maven should resolve this correctly. I use maven 3.0.5.

Can you please confirm us that you are experiencing this bug over [f93d9b8afc77e8fcaac8d2d0f116fee8af0c1a1e](https://github.com/Stratio/cassandra-lucene-index/commit/f93d9b8afc77e8fcaac8d2d0f116fee8af0c1a1e) or close this issue if you have resolved it?

Hope this helps
