### ISSUE TITLE
issue while adding plugin with cassandra

### ISSUE THREAD

**Issue by swaritras** [Stratio/cassandra-lucene-index#356]
2017-08-16 19:53:05,015 ColumnFamilyStore.java:396 - Initializing demo.tweets
ERROR [main] 2017-08-16 19:53:05,764 CassandraDaemon.java:727 - Exception encountered during startup
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:424) ~[apache-cassandra-3.6.jar:3.6]
at org.apache.cassandra.index.SecondaryIndexManager.createIndex(SecondaryIndexManager.java:159) ~[apache-cassandra-3.6.jar:3.6]
at org.apache.cassandra.index.SecondaryIndexManager.addIndex(SecondaryIndexManager.java:185) ~[apache-cassandra-3.6.jar:3.6]
at org.apache.cassandra.db.ColumnFamilyStore.(ColumnFamilyStore.java:420) ~[apache-cassandra-3.6.jar:3.6]
at org.apache.cassandra.db.ColumnFamilyStore.(ColumnFamilyStore.java:368) ~[apache-cassandra-3.6.jar:3.6]
at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:578) ~[apache-cassandra-3.6.jar:3.6]
at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:555) ~[apache-cassandra-3.6.jar:3.6]
at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:383) ~[apache-cassandra-3.6.jar:3.6]
at org.apache.cassandra.db.Keyspace.(Keyspace.java:320) ~[apache-cassandra-3.6.jar:3.6]
at org.apache.cassandra.db.Keyspace.open(Keyspace.java:130) ~[apache-cassandra-3.6.jar:3.6]
at org.apache.cassandra.db.Keyspace.open(Keyspace.java:107) ~[apache-cassandra-3.6.jar:3.6]
at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:277) [apache-cassandra-3.6.jar:3.6]
at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:581) [apache-cassandra-3.6.jar:3.6]
at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:710) [apache-cassandra-3.6.jar:3.6]
Caused by: java.lang.reflect.InvocationTargetException: null
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_131]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_131]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_131]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_131]
at org.apache.cassandra.index.SecondaryIndexManager.createInstance(SecondaryIndexManager.java:420) ~[apache-cassandra-3.6.jar:3.6]
... 13 common frames omitted
Caused by: java.lang.NoSuchMethodError: org.apache.cassandra.config.CFMetaData.primaryKeyColumns()Ljava/lang/Iterable;
at com.stratio.cassandra.lucene.IndexService.(IndexService.scala:65) ~[cassandra-lucene-index-plugin-3.10.0.jar:na]
at com.stratio.cassandra.lucene.IndexServiceSkinny.(IndexServiceSkinny.scala:37) ~[cassandra-lucene-index-plugin-3.10.0.jar:na]
at com.stratio.cassandra.lucene.IndexService$.build(IndexService.scala:434) ~[cassandra-lucene-index-plugin-3.10.0.jar:na]
at com.stratio.cassandra.lucene.Index.liftedTree1$1(Index.scala:55) ~[cassandra-lucene-index-plugin-3.10.0.jar:na]
at com.stratio.cassandra.lucene.Index.(Index.scala:55) ~[cassandra-lucene-index-plugin-3.10.0.jar:na]
... 18 common frames omitted

**Comment by jpgilaberte** [comment]
Hi @swaritras,

Thank you for your interest in the project.

I think you should try the version of the plugin aligned with the Cassandra version. In your case, you are using version 3.6 of Cassandra and version 3.10 of the plugin. With the version 3.6.0 of the plugin works correctly.

Hope this helps
Regards
