### ISSUE TITLE
Invalid bitemporal data prevents cassandra from starting up

### ISSUE THREAD

**Issue by harkanJ** [Stratio/cassandra-lucene-index#36]
Invalid time ranges (where the from is later than the to) prevent cassandra from starting up while replaying the commit log.  In the short term, is there a way to correct this with the cluster offline?  Longer term, I would think this shouldn't prevent the cluster from even starting up.

```
ERROR [main] 2015-08-25 08:04:48,502 CassandraDaemon.java:541 - Exception encountered during startup
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.stratio.cassandra.lucene.IndexException: Error while indexing row java.nio.HeapByteBuffer[pos=0 lim=4 cap=4] in Lucene index onestore.bt.bt_index
        at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:403) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.utils.FBUtilities.waitOnFutures(FBUtilities.java:392) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.commitlog.CommitLogReplayer.recover(CommitLogReplayer.java:463) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.commitlog.CommitLogReplayer.recover(CommitLogReplayer.java:119) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.commitlog.CommitLog.recover(CommitLog.java:148) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.commitlog.CommitLog.recover(CommitLog.java:128) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:352) [apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:524) [apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:613) [apache-cassandra-2.1.8.jar:2.1.8]
Caused by: java.util.concurrent.ExecutionException: com.stratio.cassandra.lucene.IndexException: Error while indexing row java.nio.HeapByteBuffer[pos=0 lim=4 cap=4] in Lucene index onestore.bt.bt_index
        at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.get(AbstractTracingAwareExecutorService.java:200) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:399) ~[apache-cassandra-2.1.8.jar:2.1.8]
        ... 8 common frames omitted
Caused by: com.stratio.cassandra.lucene.IndexException: Error while indexing row java.nio.HeapByteBuffer[pos=0 lim=4 cap=4] in Lucene index onestore.bt.bt_index
        at com.stratio.cassandra.lucene.Index.index(Index.java:159) ~[cassandra-lucene-index-plugin-2.1.8.2.jar:na]
        at org.apache.cassandra.db.index.SecondaryIndexManager$StandardUpdater.updateRowLevelIndexes(SecondaryIndexManager.java:834) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.AtomicBTreeColumns.addAllWithSizeDelta(AtomicBTreeColumns.java:229) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Memtable.put(Memtable.java:210) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1237) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:400) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:363) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.commitlog.CommitLogReplayer$1.runMayThrow(CommitLogReplayer.java:455) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_51]
        at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at java.lang.Thread.run(Thread.java:744) ~[na:1.7.0_51]
Caused by: java.lang.IllegalArgumentException: Wrong order: 2014-01-01T05 TO 2013-01-01T05:00:00.000
        at org.apache.lucene.spatial.prefix.tree.NumberRangePrefixTree.toRangeShape(NumberRangePrefixTree.java:109) ~[cassandra-lucene-index-plugin-2.1.8.2.jar:na]
        at com.stratio.cassandra.lucene.schema.mapping.BitemporalMapper.makeShape(BitemporalMapper.java:282) ~[cassandra-lucene-index-plugin-2.1.8.2.jar:na]
        at com.stratio.cassandra.lucene.schema.mapping.BitemporalMapper.addFields(BitemporalMapper.java:329) ~[cassandra-lucene-index-plugin-2.1.8.2.jar:na]
        at com.stratio.cassandra.lucene.schema.Schema.addFields(Schema.java:185) ~[cassandra-lucene-index-plugin-2.1.8.2.jar:na]
        at com.stratio.cassandra.lucene.service.RowMapperWide.document(RowMapperWide.java:107) ~[cassandra-lucene-index-plugin-2.1.8.2.jar:na]
        at com.stratio.cassandra.lucene.service.RowServiceWide.documents(RowServiceWide.java:129) ~[cassandra-lucene-index-plugin-2.1.8.2.jar:na]
        at com.stratio.cassandra.lucene.service.RowServiceWide.index(RowServiceWide.java:91) ~[cassandra-lucene-index-plugin-2.1.8.2.jar:na]
        at com.stratio.cassandra.lucene.Index.index(Index.java:154) ~[cassandra-lucene-index-plugin-2.1.8.2.jar:na]
```

**Comment by adelapena** [comment]
Hi,

We have just released [a new version of the plugin](https://github.com/Stratio/cassandra-lucene-index/tree/2.1.8.4). This new release fixes the bug and also ensures that failing indexes don't prevent Cassandra to starting up.

However, the new release index uses a much faster data format which is not compatible with previous versions, so you must drop the index and create it again after upgrading to the new plugin version.

Thanks!

**Comment by harkanJ** [comment]
Thanks!   That worked.   Though I have another issue related to the number of records returning from a bitemporal query but I'll raise that as a separate issue.
