### ISSUE TITLE
Plugin does not work with latest version of DSE 4.8.3

### ISSUE THREAD

**Issue by boardmaster357** [Stratio/cassandra-lucene-index#75]
The plugin does not work with DSE and appears to break the installation rather badly.
I am using DSE 4.8.3 based on cassandra 2.1.11.x.
I am using the plugin version 2.1.11.1
When I try to create an index, the creation fails, breaking cassandra.
It does not create the index completely and hence can not be deleted.
Once you restart cassandra, the restart will fail with the exception shown below.
Deleting the plugin does not fix the issue as starting cassandra will fail with a different error.
Only way to resolve the issue seems to be deleting all cassandra data and starting over without the plugin.

Exception is shown below.
java.lang.VerifyError: Cannot inherit from final class
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_91]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[na:1.7.0_91]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_91]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_91]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_91]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.7.0_91]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_91]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_91]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_91]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_91]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_91]
        at org.apache.lucene.codecs.appending.AppendingCodec.<init>(AppendingCodec.java:40) ~[solr-uber-with-auth_2.0-4.10.3.1.263.jar:na]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_91]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_91]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_91]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_91]
        at java.lang.Class.newInstance(Class.java:383) ~[na:1.7.0_91]
        at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:67) ~[cassandra-lucene-index-plugin-2.1.11.1.jar:na]
        at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:47) ~[cassandra-lucene-index-plugin-2.1.11.1.jar:na]
        at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:37) ~[cassandra-lucene-index-plugin-2.1.11.1.jar:na]
        at org.apache.lucene.codecs.Codec$Holder.<clinit>(Codec.java:47) ~[cassandra-lucene-index-plugin-2.1.11.1.jar:na]
        at org.apache.lucene.codecs.Codec.getDefault(Codec.java:140) ~[cassandra-lucene-index-plugin-2.1.11.1.jar:na]
        at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:120) ~[cassandra-lucene-index-plugin-2.1.11.1.jar:na]
        at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:140) ~[cassandra-lucene-index-plugin-2.1.11.1.jar:na]
        at com.stratio.cassandra.lucene.service.LuceneIndex.<init>(LuceneIndex.java:80) ~[cassandra-lucene-index-plugin-2.1.11.1.jar:na]
        at com.stratio.cassandra.lucene.service.RowService.<init>(RowService.java:99) ~[cassandra-lucene-index-plugin-2.1.11.1.jar:na]
        at com.stratio.cassandra.lucene.service.RowServiceSkinny.<init>(RowServiceSkinny.java:62) ~[cassandra-lucene-index-plugin-2.1.11.1.jar:na]
        at com.stratio.cassandra.lucene.service.RowService.build(RowService.java:116) ~[cassandra-lucene-index-plugin-2.1.11.1.jar:na]
        at com.stratio.cassandra.lucene.Index.init(Index.java:102) ~[cassandra-lucene-index-plugin-2.1.11.1.jar:na]
        at org.apache.cassandra.db.index.SecondaryIndexManager.addIndexedColumn(SecondaryIndexManager.java:299) ~[cassandra-all-2.1.11.969.jar:2.1.11.969]
        at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:386) ~[cassandra-all-2.1.11.969.jar:2.1.11.969]
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:523) ~[cassandra-all-2.1.11.969.jar:2.1.11.969]
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:494) ~[cassandra-all-2.1.11.969.jar:2.1.11.969]
        at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:335) ~[cassandra-all-2.1.11.969.jar:2.1.11.969]
        at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:275) ~[cassandra-all-2.1.11.969.jar:2.1.11.969]
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:121) ~[cassandra-all-2.1.11.969.jar:2.1.11.969]
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:98) ~[cassandra-all-2.1.11.969.jar:2.1.11.969]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:328) ~[cassandra-all-2.1.11.969.jar:2.1.11.969]
        at com.datastax.bdp.server.DseDaemon.setup(DseDaemon.java:335) ~[dse-core-4.8.3.jar:4.8.3]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:562) ~[cassandra-all-2.1.11.969.jar:2.1.11.969]
        at com.datastax.bdp.DseModule.main(DseModule.java:74) [dse-core-4.8.3.jar:4.8.3]

**Comment by adelapena** [comment]
Hi,

This project is intended to be used with Apache Cassandra. Unfortunately, DSE is not an open source project, so we can't provide support for it. Its [license doesn't allow to reverse engineer it](http://www.datastax.com/developer-license-terms), but I can suppose that there is a dependency conflict between Lucene versions. DSE 4.8.3 [seems to use Lucene 4.10.3](https://docs.datastax.com/en/datastax_enterprise/4.8/datastax_enterprise/RNdse.html), whereas Stratio's plugin 2.1.11.1 uses Lucene 5.3.0.

**Comment by boardmaster357** [comment]
I will have to stick with Apache Cassandra/cassandra-lucene-index over DSE then.  I was hoping the plugin would work with DSE, but it looks like it will not.
